-- Registre des défauts prouvés et encore ouverts (AUD-A02).
--
-- Tant qu'un couple (fichier, identifiant) figure ici, son test PEUT échouer sans
-- casser la CI. Dès qu'il passe, `_audit_assert` fait échouer la CI : le commit du
-- correctif doit supprimer la ligne. Un test qui échoue sans figurer ici casse la CI.
-- Une ligne par défaut : on en supprime une sans toucher aux autres.
--
-- AUD-X01 : la clé est le couple (file, test_id), jamais le seul test_id. Treize
-- fichiers emploient les identifiants `T01`…`T07` ; indexer sur `test_id` seul
-- blanchirait le `T01` de tous les autres fichiers.
--
-- Plan : doc/audit/PLAN-CORRECTIF-AUDIT-2026-09-21.md

-- 178 — noyau de saisie (lot C)
-- 180 — ventes (lot E)
-- 181 — paie (lot F)
-- 182 — inscription (lot B)

-- 231 — temps passés (M-17)
-- 245 — déclaration de TVA (M-10)
--
-- Ces deux lignes portaient les deux derniers défauts ouverts du plan correctif.
-- Elles sont fermées — le registre est donc **VIDE** :
--
--   • `231 M-17-01` — la refacturation des temps n'existait pas
--     (`create_billable_line_on_timesheet_stop` ne créait qu'une notification).
--     Fermé le 28/09/2026 par la **301** : brouillon de facture par projet,
--     ligne rattachée au temps (unicité société + temps), branchement sur
--     l'INSERT pour la saisie directe et sur l'arrêt du chronomètre.
--   • `245 T08` — le chiffre d'affaires non taxé (exonéré, export, livraison
--     intracommunautaire) n'entrait pas dans le CA déclaré, reconstitué depuis
--     la TVA. Fermé le 28/09/2026 par la **300** : le CA se lit sur les comptes
--     de produits (classe 70), la TVA reste lue sur les comptes 445x.
--
-- Plus aucun scénario n'a le droit d'échouer : un échec hors registre casse la
-- CI, et un défaut connu doit s'inscrire ici avec sa raison — puis disparaître
-- avec son correctif.
