-- ============================================
-- SEED STANDARD CHART OF ACCOUNTS FOR TENANTS
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================
-- PROBLEM: bootstrap_tenant() copies chart_accounts from a template
-- tenant (00000000-0000-0000-0000-000000000001) that has NO accounts.
-- New tenants get an empty chart of accounts.
--
-- FIX: Create a self-contained seed_standard_chart() function that
-- inserts the full French PCG (Plan Comptable General) directly,
-- without depending on a template tenant. Then patch bootstrap_tenant()
-- to call it. Also backfill existing tenants that are missing accounts.
--
-- PREREQUISITES:
--   - multi_tenant_migration.sql
--   - 01_fix_tenant_unique_constraints.sql
--   - 02_bootstrap_tenant.sql
-- ============================================

-- ============================================
-- 1. CREATE seed_standard_chart() FUNCTION
-- ============================================
CREATE OR REPLACE FUNCTION seed_standard_chart(p_tenant_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO chart_accounts (code, name, type, balance, tenant_id)
  VALUES
    -- Classe 1 - Capitaux
    ('101000', 'Capital social', 'equity', 0, p_tenant_id),
    ('101100', 'Capital non appele', 'equity', 0, p_tenant_id),
    ('104000', 'Primes liees au capital social', 'equity', 0, p_tenant_id),
    ('106000', 'Reserves', 'equity', 0, p_tenant_id),
    ('106100', 'Reserve legale', 'equity', 0, p_tenant_id),
    ('106800', 'Autres reserves', 'equity', 0, p_tenant_id),
    ('108000', 'Compte de l exploitant', 'equity', 0, p_tenant_id),
    ('109000', 'Actionnaires - capital souscrit non appele', 'equity', 0, p_tenant_id),
    ('110000', 'Report a nouveau (solde crediteur)', 'equity', 0, p_tenant_id),
    ('119000', 'Report a nouveau (solde debiteur)', 'equity', 0, p_tenant_id),
    ('120000', 'Resultat de l exercice (benefice)', 'equity', 0, p_tenant_id),
    ('129000', 'Resultat de l exercice (perte)', 'equity', 0, p_tenant_id),
    ('151000', 'Provisions pour risques', 'liability', 0, p_tenant_id),
    ('153000', 'Provisions pour pensions', 'liability', 0, p_tenant_id),
    ('158000', 'Autres provisions pour charges', 'liability', 0, p_tenant_id),
    ('163000', 'Emprunts aupres des etablissements de credit', 'liability', 0, p_tenant_id),
    ('164000', 'Emprunts aupres des autres partenaires', 'liability', 0, p_tenant_id),
    ('165000', 'Depots et cautionnements recus', 'liability', 0, p_tenant_id),
    ('168000', 'Autres emprunts et dettes assimilees', 'liability', 0, p_tenant_id),
    ('171000', 'Dettes rattachees a des participations', 'liability', 0, p_tenant_id),
    ('181000', 'Comptes de liaison etablissements', 'liability', 0, p_tenant_id),
    ('186000', 'Biens en credit-bail', 'liability', 0, p_tenant_id),
    ('187000', 'Biens en credit-bail - contrepartie', 'liability', 0, p_tenant_id),
    ('188000', 'Biens en location-vente', 'liability', 0, p_tenant_id),
    ('189000', 'Biens en location-vente - contrepartie', 'liability', 0, p_tenant_id),
    -- Classe 2 - Immobilisations
    ('201000', 'Frais d etablissement', 'asset', 0, p_tenant_id),
    ('205000', 'Concessions, brevets, licences, logiciels', 'asset', 0, p_tenant_id),
    ('206000', 'Droit au bail', 'asset', 0, p_tenant_id),
    ('207000', 'Fonds commercial', 'asset', 0, p_tenant_id),
    ('208000', 'Autres immobilisations incorporelles', 'asset', 0, p_tenant_id),
    ('210000', 'Terrains', 'asset', 0, p_tenant_id),
    ('211000', 'Agencements et ameliororations de terrains', 'asset', 0, p_tenant_id),
    ('212000', 'Constructions', 'asset', 0, p_tenant_id),
    ('213000', 'Constructions sur sol d autrui', 'asset', 0, p_tenant_id),
    ('215000', 'Installations techniques, materiels et outillage', 'asset', 0, p_tenant_id),
    ('215400', 'Materiel industriel', 'asset', 0, p_tenant_id),
    ('218000', 'Materiel informatique', 'asset', 0, p_tenant_id),
    ('218100', 'Materiel de bureau et informatique', 'asset', 0, p_tenant_id),
    ('218200', 'Mobilier', 'asset', 0, p_tenant_id),
    ('218300', 'Materiel de bureau', 'asset', 0, p_tenant_id),
    ('218400', 'Materiel et outillage', 'asset', 0, p_tenant_id),
    ('218500', 'Embages et equipements', 'asset', 0, p_tenant_id),
    ('220000', 'Immobilisations corporelles en cours', 'asset', 0, p_tenant_id),
    ('230000', 'Immobilisations en cours - incorporelles', 'asset', 0, p_tenant_id),
    ('231000', 'Immobilisations en cours - corporelles', 'asset', 0, p_tenant_id),
    ('238000', 'Avances et acomptes verses sur commandes', 'asset', 0, p_tenant_id),
    ('240000', 'Participations et creances rattachees', 'asset', 0, p_tenant_id),
    ('250000', 'Titres de participation', 'asset', 0, p_tenant_id),
    ('260000', 'Titres immobilises', 'asset', 0, p_tenant_id),
    ('270000', 'Participations et creances rattachees (droit de propriete)', 'asset', 0, p_tenant_id),
    ('271000', 'Titres immobilises (droit de propriete)', 'asset', 0, p_tenant_id),
    ('275000', 'Depots et cautionnements verses', 'asset', 0, p_tenant_id),
    ('280000', 'Amortissements des immobilisations incorporelles', 'asset', 0, p_tenant_id),
    ('280500', 'Amortissements des concessions, brevets, licences, logiciels', 'asset', 0, p_tenant_id),
    ('281000', 'Amortissements des immobilisations corporelles', 'asset', 0, p_tenant_id),
    ('281200', 'Amortissements des constructions', 'asset', 0, p_tenant_id),
    ('281500', 'Amortissements des installations techniques', 'asset', 0, p_tenant_id),
    ('281800', 'Amortissements du materiel', 'asset', 0, p_tenant_id),
    ('290000', 'Depreciations des immobilisations incorporelles', 'asset', 0, p_tenant_id),
    ('291000', 'Depreciations des immobilisations corporelles', 'asset', 0, p_tenant_id),
    ('293000', 'Depreciations des immobilisations en cours', 'asset', 0, p_tenant_id),
    ('296000', 'Depreciations des participations et creances rattachees', 'asset', 0, p_tenant_id),
    ('297000', 'Depreciations des autres immobilisations financieres', 'asset', 0, p_tenant_id),
    -- Classe 3 - Stocks
    ('310000', 'Matieres premieres (et fournitures)', 'asset', 0, p_tenant_id),
    ('320000', 'Matieres consommables', 'asset', 0, p_tenant_id),
    ('321000', 'Matieres consommables', 'asset', 0, p_tenant_id),
    ('322000', 'Fournitures consommables', 'asset', 0, p_tenant_id),
    ('330000', 'En-cours de production de biens', 'asset', 0, p_tenant_id),
    ('340000', 'Etudes en cours', 'asset', 0, p_tenant_id),
    ('345000', 'Travaux en cours', 'asset', 0, p_tenant_id),
    ('350000', 'Produits intermediaires et finis', 'asset', 0, p_tenant_id),
    ('351000', 'Produits intermediaires', 'asset', 0, p_tenant_id),
    ('352000', 'Produits finis', 'asset', 0, p_tenant_id),
    ('354000', 'Produits residuels', 'asset', 0, p_tenant_id),
    ('355000', 'Produits finis (group A)', 'asset', 0, p_tenant_id),
    ('358000', 'Produits finis (group B)', 'asset', 0, p_tenant_id),
    ('360000', 'Stocks provenant d immobilisations', 'asset', 0, p_tenant_id),
    ('370000', 'Stocks de marchandises', 'asset', 0, p_tenant_id),
    ('371000', 'Marchandises (group A)', 'asset', 0, p_tenant_id),
    ('372000', 'Marchandises (group B)', 'asset', 0, p_tenant_id),
    ('380000', 'Stocks a tres rapide rotation', 'asset', 0, p_tenant_id),
    ('390000', 'Depreciations des stocks', 'asset', 0, p_tenant_id),
    ('391000', 'Depreciations des matieres premieres', 'asset', 0, p_tenant_id),
    ('392000', 'Depreciations des matieres consommables', 'asset', 0, p_tenant_id),
    ('393000', 'Depreciations des en-cours de production', 'asset', 0, p_tenant_id),
    ('395000', 'Depreciations des produits', 'asset', 0, p_tenant_id),
    ('397000', 'Depreciations des marchandises', 'asset', 0, p_tenant_id),
    -- Classe 4 - Tiers
    ('400000', 'Fournisseurs et comptes rattaches', 'liability', 0, p_tenant_id),
    ('401000', 'Fournisseurs', 'liability', 0, p_tenant_id),
    ('401100', 'Fournisseurs - achats de biens et services', 'liability', 0, p_tenant_id),
    ('401700', 'Fournisseurs - retenues de garantie', 'liability', 0, p_tenant_id),
    ('403000', 'Fournisseurs - effets a payer', 'liability', 0, p_tenant_id),
    ('404000', 'Fournisseurs d immobilisations', 'liability', 0, p_tenant_id),
    ('405000', 'Fournisseurs d immobilisations - effets a payer', 'liability', 0, p_tenant_id),
    ('408000', 'Fournisseurs - factures non parvenues', 'liability', 0, p_tenant_id),
    ('408100', 'Fournisseurs - factures non parvenues (biens et services)', 'liability', 0, p_tenant_id),
    ('408400', 'Fournisseurs - factures non parvenues (immobilisations)', 'liability', 0, p_tenant_id),
    ('409000', 'Fournisseurs debiteurs', 'asset', 0, p_tenant_id),
    ('409100', 'Fournisseurs - avances et acomptes verses', 'asset', 0, p_tenant_id),
    ('409600', 'Fournisseurs - avoirs a recevoir', 'asset', 0, p_tenant_id),
    ('409700', 'Fournisseurs - autres avoirs', 'asset', 0, p_tenant_id),
    ('410000', 'Clients et comptes rattaches', 'asset', 0, p_tenant_id),
    ('411000', 'Clients', 'asset', 0, p_tenant_id),
    ('411100', 'Clients - ventes de biens et services', 'asset', 0, p_tenant_id),
    ('411700', 'Clients - retenues de garantie', 'asset', 0, p_tenant_id),
    ('413000', 'Clients - effets a recevoir', 'asset', 0, p_tenant_id),
    ('416000', 'Clients douteux ou litigieux', 'asset', 0, p_tenant_id),
    ('417000', 'Clients - creances sur travaux non encore facturables', 'asset', 0, p_tenant_id),
    ('418000', 'Clients - produits non encore factures', 'asset', 0, p_tenant_id),
    ('419000', 'Clients crediteurs', 'liability', 0, p_tenant_id),
    ('419100', 'Clients - avances et acomptes recus', 'liability', 0, p_tenant_id),
    ('419600', 'Clients - avoirs a etablir', 'liability', 0, p_tenant_id),
    ('419700', 'Clients - autres avoirs a etablir', 'liability', 0, p_tenant_id),
    ('420000', 'Personnel et comptes rattaches', 'liability', 0, p_tenant_id),
    ('421000', 'Personnel - remunerations dues', 'liability', 0, p_tenant_id),
    ('422000', 'Comites d entreprise, d etablissement, etc.', 'liability', 0, p_tenant_id),
    ('424000', 'Participation des salaries aux resultats', 'liability', 0, p_tenant_id),
    ('425000', 'Personnel - avances et acomptes', 'asset', 0, p_tenant_id),
    ('426000', 'Personnel - depots', 'liability', 0, p_tenant_id),
    ('427000', 'Personnel - oppositions', 'liability', 0, p_tenant_id),
    ('428000', 'Personnel - charges a payer et produits a recevoir', 'liability', 0, p_tenant_id),
    ('428200', 'Conges payes', 'liability', 0, p_tenant_id),
    ('428400', 'Comptes courants des salaries', 'liability', 0, p_tenant_id),
    ('428600', 'Personnel - produits a recevoir', 'asset', 0, p_tenant_id),
    ('430000', 'Securite sociale et autres organismes sociaux', 'liability', 0, p_tenant_id),
    ('431000', 'Securite sociale', 'liability', 0, p_tenant_id),
    ('432000', 'Autres organismes sociaux', 'liability', 0, p_tenant_id),
    ('437000', 'Autres organismes sociaux', 'liability', 0, p_tenant_id),
    ('438000', 'Organismes sociaux - charges a payer et produits a recevoir', 'liability', 0, p_tenant_id),
    ('438200', 'Charges de securite sociale et de prevoyance', 'liability', 0, p_tenant_id),
    ('438600', 'Organismes sociaux - produits a recevoir', 'asset', 0, p_tenant_id),
    ('440000', 'Etat et autres collectivites publiques', 'liability', 0, p_tenant_id),
    ('441000', 'Etat - subventions a recevoir', 'asset', 0, p_tenant_id),
    ('442000', 'Etat - impots et taxes recuperables', 'asset', 0, p_tenant_id),
    ('443000', 'Operations particulieres avec l Etat', 'liability', 0, p_tenant_id),
    ('444000', 'Etat - impots sur les benefices', 'liability', 0, p_tenant_id),
    ('445000', 'Etat - taxes sur le chiffre d affaires', 'liability', 0, p_tenant_id),
    ('445200', 'TVA due intracommunautaire', 'liability', 0, p_tenant_id),
    ('445510', 'TVA a deduire (biens et services)', 'asset', 0, p_tenant_id),
    ('445560', 'TVA a dedeductible (autres biens et services)', 'asset', 0, p_tenant_id),
    ('445570', 'TVA deductible (immobilisations)', 'asset', 0, p_tenant_id),
    ('445620', 'TVA due (biens et services)', 'liability', 0, p_tenant_id),
    ('445660', 'TVA deductible', 'liability', 0, p_tenant_id),
    ('445670', 'TVA deductible (immobilisations)', 'liability', 0, p_tenant_id),
    ('445710', 'TVA collectee', 'liability', 0, p_tenant_id),
    ('445800', 'TVA a regulariser', 'liability', 0, p_tenant_id),
    ('447000', 'Autres impots, taxes et versements assimiles', 'liability', 0, p_tenant_id),
    ('448000', 'Etat - charges a payer et produits a recevoir', 'liability', 0, p_tenant_id),
    ('448200', 'Etat - charges a payer', 'liability', 0, p_tenant_id),
    ('448600', 'Etat - produits a recevoir', 'asset', 0, p_tenant_id),
    ('449000', 'Etat - subventions a reverser', 'liability', 0, p_tenant_id),
    ('450000', 'Groupes et associes', 'liability', 0, p_tenant_id),
    ('451000', 'Groupes', 'liability', 0, p_tenant_id),
    ('455000', 'Associes - comptes courants', 'liability', 0, p_tenant_id),
    ('456000', 'Associes - operations sur le capital', 'liability', 0, p_tenant_id),
    ('456100', 'Associes - apports en nature', 'liability', 0, p_tenant_id),
    ('456200', 'Associes - apports en numeraire', 'liability', 0, p_tenant_id),
    ('456300', 'Associes - versements restant a effectuer', 'liability', 0, p_tenant_id),
    ('456400', 'Associes - versements anticipes', 'asset', 0, p_tenant_id),
    ('457000', 'Associes - dividendes a payer', 'liability', 0, p_tenant_id),
    ('458000', 'Associes - operations faites en commun', 'liability', 0, p_tenant_id),
    ('460000', 'Debiteurs divers et crediteurs divers', 'asset', 0, p_tenant_id),
    ('461000', 'Debiteurs divers', 'asset', 0, p_tenant_id),
    ('462000', 'Crediteurs divers', 'liability', 0, p_tenant_id),
    ('463000', 'Debiteurs et crediteurs divers', 'asset', 0, p_tenant_id),
    ('464000', 'Debiteurs et crediteurs divers', 'liability', 0, p_tenant_id),
    ('465000', 'Comptes de liaison des etablissements', 'liability', 0, p_tenant_id),
    ('467000', 'Autres comptes debiteurs ou crediteurs', 'asset', 0, p_tenant_id),
    ('468000', 'Divers - charges a payer et produits a recevoir', 'liability', 0, p_tenant_id),
    ('468600', 'Divers - produits a recevoir', 'asset', 0, p_tenant_id),
    ('468700', 'Divers - charges a payer', 'liability', 0, p_tenant_id),
    ('470000', 'Comptes d attente', 'liability', 0, p_tenant_id),
    ('471000', 'Comptes d attente', 'liability', 0, p_tenant_id),
    ('480000', 'Comptes de regularisation', 'liability', 0, p_tenant_id),
    ('481000', 'Charges constatees d avance', 'asset', 0, p_tenant_id),
    ('486000', 'Charges reparties dans le temps', 'asset', 0, p_tenant_id),
    ('487000', 'Produits constates d avance', 'liability', 0, p_tenant_id),
    ('488000', 'Comptes de repartition periodique des charges et produits', 'liability', 0, p_tenant_id),
    ('490000', 'Depreciations des comptes de clients', 'asset', 0, p_tenant_id),
    ('491000', 'Depreciations des comptes de clients', 'asset', 0, p_tenant_id),
    ('495000', 'Depreciations des comptes de debiteurs divers', 'asset', 0, p_tenant_id),
    ('496000', 'Depreciations des creances diverses', 'asset', 0, p_tenant_id),
    -- Classe 5 - Comptes financiers
    ('500000', 'Valeurs mobilieres de placement', 'asset', 0, p_tenant_id),
    ('501000', 'Titres de placement', 'asset', 0, p_tenant_id),
    ('502000', 'Actions propres', 'asset', 0, p_tenant_id),
    ('503000', 'Actions', 'asset', 0, p_tenant_id),
    ('504000', 'Obligations', 'asset', 0, p_tenant_id),
    ('505000', 'Bons du Tresor et bons de caisse', 'asset', 0, p_tenant_id),
    ('506000', 'Obligations et bons emis par la societe', 'asset', 0, p_tenant_id),
    ('507000', 'Bons du Tresor et bons de caisse (emis par la societe)', 'asset', 0, p_tenant_id),
    ('508000', 'Autres valeurs mobilieres de placement', 'asset', 0, p_tenant_id),
    ('509000', 'Versements restant a effectuer sur VMP', 'liability', 0, p_tenant_id),
    ('510000', 'Banques, etablissements financiers et assimiles', 'asset', 0, p_tenant_id),
    ('511000', 'Valeurs a l encaissement', 'asset', 0, p_tenant_id),
    ('511100', 'Coupons echus non encaisses', 'asset', 0, p_tenant_id),
    ('511200', 'Dividendes a encaisser', 'asset', 0, p_tenant_id),
    ('511300', 'Effets a encaisser', 'asset', 0, p_tenant_id),
    ('511400', 'Effets a l encaissement', 'asset', 0, p_tenant_id),
    ('511500', 'Effets remis a l escompte', 'asset', 0, p_tenant_id),
    ('512000', 'Banque', 'asset', 0, p_tenant_id),
    ('512100', 'Comptes en monnaie nationale', 'asset', 0, p_tenant_id),
    ('512400', 'Comptes en devises', 'asset', 0, p_tenant_id),
    ('514000', 'Banques - etablissements financiers', 'asset', 0, p_tenant_id),
    ('515000', 'Caisses du Tresor et des PTT', 'asset', 0, p_tenant_id),
    ('516000', 'Societes de bourse', 'asset', 0, p_tenant_id),
    ('517000', 'Banques a l etranger', 'asset', 0, p_tenant_id),
    ('518000', 'Interets courus a payer', 'liability', 0, p_tenant_id),
    ('518100', 'Interets courus a payer (emprunts)', 'liability', 0, p_tenant_id),
    ('518600', 'Interets courus a recevoir', 'asset', 0, p_tenant_id),
    ('518800', 'Interets courus a payer (autres)', 'liability', 0, p_tenant_id),
    ('519000', 'Concours bancaires courants', 'liability', 0, p_tenant_id),
    ('519100', 'Credit de mobilisation de creances commerciales', 'liability', 0, p_tenant_id),
    ('519300', 'Mobilisation de creances nes a l etranger', 'liability', 0, p_tenant_id),
    ('519400', 'Autres concours bancaires courants', 'liability', 0, p_tenant_id),
    ('519500', 'Credit de mobilisation de creances commerciales (escompte)', 'liability', 0, p_tenant_id),
    ('519700', 'Autres concours bancaires courants', 'liability', 0, p_tenant_id),
    ('520000', 'Instruments de tresorerie', 'asset', 0, p_tenant_id),
    ('521000', 'Instruments de tresorerie - droits', 'asset', 0, p_tenant_id),
    ('522000', 'Instruments de tresorerie - obligations', 'liability', 0, p_tenant_id),
    ('530000', 'Caisse', 'asset', 0, p_tenant_id),
    ('531000', 'Caisse - siege social', 'asset', 0, p_tenant_id),
    ('532000', 'Caisse - succursale ou usine', 'asset', 0, p_tenant_id),
    ('535000', 'Caisse - etablissement a l etranger', 'asset', 0, p_tenant_id),
    ('540000', 'Regies d avances et accréditifs', 'asset', 0, p_tenant_id),
    ('550000', 'Caisse - monnaies etrangeres', 'asset', 0, p_tenant_id),
    ('580000', 'Virements internes', 'asset', 0, p_tenant_id),
    ('590000', 'Depreciations des comptes financiers', 'asset', 0, p_tenant_id),
    ('590100', 'Depreciations des VMP', 'asset', 0, p_tenant_id),
    ('590800', 'Depreciations des autres valeurs mobilieres', 'asset', 0, p_tenant_id),
    -- Classe 6 - Charges
    ('600000', 'Achats (sauf 603)', 'expense', 0, p_tenant_id),
    ('601000', 'Achats de matieres premieres', 'expense', 0, p_tenant_id),
    ('601100', 'Achats de matieres premieres (group A)', 'expense', 0, p_tenant_id),
    ('601200', 'Achats de matieres premieres (group B)', 'expense', 0, p_tenant_id),
    ('602000', 'Achats de matieres consommables', 'expense', 0, p_tenant_id),
    ('602100', 'Achats de matieres consommables', 'expense', 0, p_tenant_id),
    ('602200', 'Achats de fournitures consommables', 'expense', 0, p_tenant_id),
    ('602210', 'Achats de fournitures de bureau', 'expense', 0, p_tenant_id),
    ('602220', 'Achats de fournitures d atelier', 'expense', 0, p_tenant_id),
    ('602400', 'Achats de combustibles', 'expense', 0, p_tenant_id),
    ('602500', 'Achats de produits d entretien', 'expense', 0, p_tenant_id),
    ('602600', 'Achats de fournitures d emballage', 'expense', 0, p_tenant_id),
    ('603000', 'Variations des stocks', 'expense', 0, p_tenant_id),
    ('603100', 'Variation des stocks de matieres premieres', 'expense', 0, p_tenant_id),
    ('603200', 'Variation des stocks de matieres et fournitures consommables', 'expense', 0, p_tenant_id),
    ('603700', 'Variation des stocks de marchandises', 'expense', 0, p_tenant_id),
    ('604000', 'Achats d etudes et de prestations de services', 'expense', 0, p_tenant_id),
    ('605000', 'Achats de materiels, equipements et travaux', 'expense', 0, p_tenant_id),
    ('606000', 'Achats non stockes de matieres et fournitures', 'expense', 0, p_tenant_id),
    ('606100', 'Fournitures non stockables (eau, energie)', 'expense', 0, p_tenant_id),
    ('606110', 'Eau', 'expense', 0, p_tenant_id),
    ('606120', 'Energie (gaz, electricite)', 'expense', 0, p_tenant_id),
    ('606130', 'Carburants', 'expense', 0, p_tenant_id),
    ('606400', 'Fournitures d entretien non stockables', 'expense', 0, p_tenant_id),
    ('606410', 'Produits d entretien', 'expense', 0, p_tenant_id),
    ('606500', 'Fournitures de bureau', 'expense', 0, p_tenant_id),
    ('606600', 'Fournitures de bureau non stockables', 'expense', 0, p_tenant_id),
    ('606800', 'Autres achats non stockes de matieres et fournitures', 'expense', 0, p_tenant_id),
    ('607000', 'Achats de marchandises', 'expense', 0, p_tenant_id),
    ('607100', 'Achats de marchandises (group A)', 'expense', 0, p_tenant_id),
    ('607200', 'Achats de marchandises (group B)', 'expense', 0, p_tenant_id),
    ('608000', 'Frais accessoires d achats', 'expense', 0, p_tenant_id),
    ('608100', 'Frais accessoires d achats sur matieres premieres', 'expense', 0, p_tenant_id),
    ('608200', 'Frais accessoires d achats sur matieres consommables', 'expense', 0, p_tenant_id),
    ('608700', 'Frais accessoires d achats sur marchandises', 'expense', 0, p_tenant_id),
    ('609000', 'Rabais, remises et ristournes obtenus sur achats', 'expense', 0, p_tenant_id),
    ('609100', 'Rabais, remises et ristournes sur achats de matieres premieres', 'expense', 0, p_tenant_id),
    ('609400', 'Rabais, remises et ristournes sur achats d etudes et prestations', 'expense', 0, p_tenant_id),
    ('609600', 'Rabais, remises et ristournes sur achats non stockes', 'expense', 0, p_tenant_id),
    ('609700', 'Rabais, remises et ristournes sur achats de marchandises', 'expense', 0, p_tenant_id),
    ('609800', 'Rabais, remises et ristournes sur frais accessoires d achats', 'expense', 0, p_tenant_id),
    ('610000', 'Services exterieurs', 'expense', 0, p_tenant_id),
    ('611000', 'Sous-traitance generale', 'expense', 0, p_tenant_id),
    ('611100', 'Sous-traitance generale', 'expense', 0, p_tenant_id),
    ('611200', 'Sous-traitance generale (group B)', 'expense', 0, p_tenant_id),
    ('611400', 'Sous-traitance generale (autres)', 'expense', 0, p_tenant_id),
    ('612000', 'Redevances de credit-bail', 'expense', 0, p_tenant_id),
    ('612100', 'Redevances de credit-bail mobilier', 'expense', 0, p_tenant_id),
    ('612200', 'Redevances de credit-bail immobilier', 'expense', 0, p_tenant_id),
    ('612500', 'Redevances de contrats de location-vente', 'expense', 0, p_tenant_id),
    ('613000', 'Locations', 'expense', 0, p_tenant_id),
    ('613100', 'Locations de terrains', 'expense', 0, p_tenant_id),
    ('613200', 'Locations de constructions', 'expense', 0, p_tenant_id),
    ('613500', 'Locations de materiels et outillages', 'expense', 0, p_tenant_id),
    ('613600', 'Locations de materiels et outillages (group B)', 'expense', 0, p_tenant_id),
    ('614000', 'Charges locatives et de copropriete', 'expense', 0, p_tenant_id),
    ('615000', 'Entretien et reparations', 'expense', 0, p_tenant_id),
    ('615100', 'Entretien et reparations de biens immobiliers', 'expense', 0, p_tenant_id),
    ('615200', 'Entretien et reparations de biens mobiliers', 'expense', 0, p_tenant_id),
    ('615500', 'Entretien et reparations de materiels', 'expense', 0, p_tenant_id),
    ('615600', 'Entretien et reparations de materiels de transport', 'expense', 0, p_tenant_id),
    ('616000', 'Assurances', 'expense', 0, p_tenant_id),
    ('616100', 'Assurances multirisques', 'expense', 0, p_tenant_id),
    ('616200', 'Assurances obligatoires dommages construction', 'expense', 0, p_tenant_id),
    ('616300', 'Assurances transports', 'expense', 0, p_tenant_id),
    ('616360', 'Assurances transports (sur achats)', 'expense', 0, p_tenant_id),
    ('616370', 'Assurances transports (sur ventes)', 'expense', 0, p_tenant_id),
    ('616400', 'Assurances risques d exploitation', 'expense', 0, p_tenant_id),
    ('616500', 'Assurances automobiles', 'expense', 0, p_tenant_id),
    ('616600', 'Assurances personnels', 'expense', 0, p_tenant_id),
    ('616800', 'Autres assurances', 'expense', 0, p_tenant_id),
    ('617000', 'Etudes et recherches', 'expense', 0, p_tenant_id),
    ('618000', 'Documentation', 'expense', 0, p_tenant_id),
    ('618100', 'Documentation generale', 'expense', 0, p_tenant_id),
    ('618200', 'Documentation technique', 'expense', 0, p_tenant_id),
    ('618300', 'Documentation commerciale', 'expense', 0, p_tenant_id),
    ('618400', 'Documentation administrative', 'expense', 0, p_tenant_id),
    ('619000', 'Rabais, remises et ristournes obtenus sur services exterieurs', 'expense', 0, p_tenant_id),
    ('620000', 'Autres services exterieurs', 'expense', 0, p_tenant_id),
    ('621000', 'Personnel exterieur a l entreprise', 'expense', 0, p_tenant_id),
    ('621100', 'Personnel integre', 'expense', 0, p_tenant_id),
    ('621400', 'Personnel detache par d autres entreprises', 'expense', 0, p_tenant_id),
    ('621600', 'Personnel exterieur a l entreprise (autres)', 'expense', 0, p_tenant_id),
    ('622000', 'Remuneration d intermediaires et honoraires', 'expense', 0, p_tenant_id),
    ('622100', 'Honoraires (non retenus par la source)', 'expense', 0, p_tenant_id),
    ('622200', 'Commissions et courtages sur achats', 'expense', 0, p_tenant_id),
    ('622400', 'Commissions et courtages sur ventes', 'expense', 0, p_tenant_id),
    ('622500', 'Frais de recouvrement', 'expense', 0, p_tenant_id),
    ('622600', 'Frais d actes et de contentieux', 'expense', 0, p_tenant_id),
    ('622700', 'Frais de reunion, de reception et de representant', 'expense', 0, p_tenant_id),
    ('622800', 'Divers', 'expense', 0, p_tenant_id),
    ('623000', 'Publicite, publications, relations publiques', 'expense', 0, p_tenant_id),
    ('623100', 'Annonces et insertions', 'expense', 0, p_tenant_id),
    ('623200', 'Echantillons, catalogues et prospectus', 'expense', 0, p_tenant_id),
    ('623300', 'Foires et expositions', 'expense', 0, p_tenant_id),
    ('623400', 'Cadeaux a la clientele', 'expense', 0, p_tenant_id),
    ('623500', 'Primes', 'expense', 0, p_tenant_id),
    ('623600', 'Catalogues et imprimes', 'expense', 0, p_tenant_id),
    ('623700', 'Publicite directe', 'expense', 0, p_tenant_id),
    ('623800', 'Divers (pourboires, etc.)', 'expense', 0, p_tenant_id),
    ('624000', 'Transports de biens et transports collectifs du personnel', 'expense', 0, p_tenant_id),
    ('624100', 'Transports sur achats', 'expense', 0, p_tenant_id),
    ('624200', 'Transports sur ventes', 'expense', 0, p_tenant_id),
    ('624300', 'Transports entre etablissements', 'expense', 0, p_tenant_id),
    ('624400', 'Transports administratifs', 'expense', 0, p_tenant_id),
    ('624700', 'Transports collectifs du personnel', 'expense', 0, p_tenant_id),
    ('625000', 'Deplacements, missions et receptions', 'expense', 0, p_tenant_id),
    ('625100', 'Voyages et deplacements', 'expense', 0, p_tenant_id),
    ('625600', 'Missions', 'expense', 0, p_tenant_id),
    ('625700', 'Receptions', 'expense', 0, p_tenant_id),
    ('626000', 'Frais postaux et de telecommunications', 'expense', 0, p_tenant_id),
    ('626100', 'Frais postaux', 'expense', 0, p_tenant_id),
    ('626300', 'Frais de telecommunications', 'expense', 0, p_tenant_id),
    ('626500', 'Frais de telecommunications (autres)', 'expense', 0, p_tenant_id),
    ('627000', 'Services bancaires et assimiles', 'expense', 0, p_tenant_id),
    ('627100', 'Frais de tenue de compte', 'expense', 0, p_tenant_id),
    ('627200', 'Commissions sur acceptation et negociation de creances', 'expense', 0, p_tenant_id),
    ('627500', 'Commissions et frais sur encaissements', 'expense', 0, p_tenant_id),
    ('627600', 'Commissions et frais sur encaissements (autres)', 'expense', 0, p_tenant_id),
    ('627800', 'Autres frais et commissions sur prestations de services', 'expense', 0, p_tenant_id),
    ('628000', 'Divers', 'expense', 0, p_tenant_id),
    ('628100', 'Concours divers (cotisations, etc.)', 'expense', 0, p_tenant_id),
    ('628400', 'Frais de recrutement de personnel', 'expense', 0, p_tenant_id),
    ('629000', 'Rabais, remises et ristournes obtenus sur autres services exterieurs', 'expense', 0, p_tenant_id),
    ('630000', 'Autres charges', 'expense', 0, p_tenant_id),
    ('631000', 'Impots, taxes et versements assimiles sur remunerations', 'expense', 0, p_tenant_id),
    ('631100', 'Impots, taxes et versements assimiles sur remunerations (administrations)', 'expense', 0, p_tenant_id),
    ('631200', 'Impots, taxes et versements assimiles sur remunerations (autres organismes)', 'expense', 0, p_tenant_id),
    ('631300', 'Participation des employeurs a la formation professionnelle continue', 'expense', 0, p_tenant_id),
    ('631400', 'Participation des employeurs a l effort de construction', 'expense', 0, p_tenant_id),
    ('631600', 'Impots, taxes et versements assimiles sur remunerations (autres)', 'expense', 0, p_tenant_id),
    ('631800', 'Autres impots, taxes et versements assimiles sur remunerations', 'expense', 0, p_tenant_id),
    ('633000', 'Impots, taxes et versements assimiles sur immobilisations', 'expense', 0, p_tenant_id),
    ('635000', 'Impots, taxes et versements assimiles sur le chiffre d affaires', 'expense', 0, p_tenant_id),
    ('635100', 'Impots, taxes et versements assimiles sur le chiffre d affaires (TVA)', 'expense', 0, p_tenant_id),
    ('635200', 'Impots, taxes et versements assimiles sur le chiffre d affaires (autres)', 'expense', 0, p_tenant_id),
    ('635300', 'Impots, taxes et versements assimiles sur le chiffre d affaires (autres)', 'expense', 0, p_tenant_id),
    ('635400', 'Impots, taxes et versements assimiles sur le chiffre d affaires (autres)', 'expense', 0, p_tenant_id),
    ('635500', 'Impots, taxes et versements assimiles sur le chiffre d affaires (autres)', 'expense', 0, p_tenant_id),
    ('635800', 'Autres impots, taxes et versements assimiles sur le chiffre d affaires', 'expense', 0, p_tenant_id),
    ('636000', 'Impots, taxes et versements assimiles sur le capital', 'expense', 0, p_tenant_id),
    ('637000', 'Autres impots, taxes et versements assimiles', 'expense', 0, p_tenant_id),
    ('637100', 'Impots, taxes et versements assimiles (autres)', 'expense', 0, p_tenant_id),
    ('637200', 'Impots, taxes et versements assimiles (autres)', 'expense', 0, p_tenant_id),
    ('637300', 'Impots, taxes et versements assimiles (autres)', 'expense', 0, p_tenant_id),
    ('637400', 'Impots, taxes et versements assimiles (autres)', 'expense', 0, p_tenant_id),
    ('637800', 'Autres impots, taxes et versements assimiles', 'expense', 0, p_tenant_id),
    ('638000', 'Autres impots, taxes et versements assimiles', 'expense', 0, p_tenant_id),
    ('639000', 'Rabais, remises et ristournes obtenus sur autres charges externes', 'expense', 0, p_tenant_id),
    ('640000', 'Charges de personnel', 'expense', 0, p_tenant_id),
    ('641000', 'Remunerations du personnel', 'expense', 0, p_tenant_id),
    ('641100', 'Apprentis', 'expense', 0, p_tenant_id),
    ('641200', 'Stagiaires', 'expense', 0, p_tenant_id),
    ('641300', 'Remunerations du personnel (autres)', 'expense', 0, p_tenant_id),
    ('641400', 'Remunerations du personnel (autres)', 'expense', 0, p_tenant_id),
    ('641500', 'Remunerations du personnel (autres)', 'expense', 0, p_tenant_id),
    ('641600', 'Remunerations du personnel (autres)', 'expense', 0, p_tenant_id),
    ('641700', 'Remunerations du personnel (autres)', 'expense', 0, p_tenant_id),
    ('641800', 'Remunerations du personnel (autres)', 'expense', 0, p_tenant_id),
    ('642000', 'Remunerations du personnel de direction', 'expense', 0, p_tenant_id),
    ('643000', 'Remunerations du personnel de direction', 'expense', 0, p_tenant_id),
    ('644000', 'Remuneration du travail de l exploitant', 'expense', 0, p_tenant_id),
    ('645000', 'Charges sociales', 'expense', 0, p_tenant_id),
    ('645100', 'Cotisations a l URSSAF', 'expense', 0, p_tenant_id),
    ('645200', 'Cotisations aux mutuelles', 'expense', 0, p_tenant_id),
    ('645300', 'Cotisations caisses de retraite', 'expense', 0, p_tenant_id),
    ('645400', 'Cotisations aux ASSEDIC', 'expense', 0, p_tenant_id),
    ('645500', 'Prevoyances', 'expense', 0, p_tenant_id),
    ('645800', 'Cotisations aux autres organismes sociaux', 'expense', 0, p_tenant_id),
    ('646000', 'Cotisations sociales personnelles de l exploitant', 'expense', 0, p_tenant_id),
    ('647000', 'Autres charges sociales', 'expense', 0, p_tenant_id),
    ('647100', 'Prestations de retraites', 'expense', 0, p_tenant_id),
    ('647200', 'Prestations directes', 'expense', 0, p_tenant_id),
    ('647300', 'Prestations de retraites (autres)', 'expense', 0, p_tenant_id),
    ('647400', 'Prestations directes (autres)', 'expense', 0, p_tenant_id),
    ('647500', 'Medecine du travail, pharmacie', 'expense', 0, p_tenant_id),
    ('647800', 'Autres charges sociales', 'expense', 0, p_tenant_id),
    ('648000', 'Autres charges de personnel', 'expense', 0, p_tenant_id),
    ('649000', 'Rabais, remises et ristournes obtenus sur charges de personnel', 'expense', 0, p_tenant_id),
    ('650000', 'Autres charges de gestion courante', 'expense', 0, p_tenant_id),
    ('651000', 'Redevances pour concessions, brevets, licences, marques, procedes, logiciels', 'expense', 0, p_tenant_id),
    ('651100', 'Redevances pour concessions, brevets, licences, marques, procedes, logiciels', 'expense', 0, p_tenant_id),
    ('651600', 'Droits d auteur', 'expense', 0, p_tenant_id),
    ('651800', 'Autres redevances', 'expense', 0, p_tenant_id),
    ('653000', 'Jetons de presence', 'expense', 0, p_tenant_id),
    ('654000', 'Pertes sur creances irrecouvrables', 'expense', 0, p_tenant_id),
    ('654100', 'Pertes sur creances clients', 'expense', 0, p_tenant_id),
    ('654400', 'Pertes sur creances autres', 'expense', 0, p_tenant_id),
    ('655000', 'Quotes-parts de resultat sur operations faites en commun', 'expense', 0, p_tenant_id),
    ('655100', 'Quotes-parts de benefice', 'expense', 0, p_tenant_id),
    ('655200', 'Quotes-parts de pertes', 'expense', 0, p_tenant_id),
    ('656000', 'Pertes de change', 'expense', 0, p_tenant_id),
    ('656100', 'Pertes de change (autres)', 'expense', 0, p_tenant_id),
    ('656600', 'Pertes de change (autres)', 'expense', 0, p_tenant_id),
    ('656800', 'Ecarts de conversion - actif', 'expense', 0, p_tenant_id),
    ('657000', 'Charges de gestion courante (autres)', 'expense', 0, p_tenant_id),
    ('658000', 'Charges diverses de gestion courante', 'expense', 0, p_tenant_id),
    ('658100', 'Pertes sur operations a terme', 'expense', 0, p_tenant_id),
    ('658200', 'Pertes sur operations de change a terme', 'expense', 0, p_tenant_id),
    ('658600', 'Autres charges diverses de gestion courante', 'expense', 0, p_tenant_id),
    ('658800', 'Rabais, remises et ristournes obtenus sur autres charges de gestion courante', 'expense', 0, p_tenant_id),
    ('660000', 'Charges financieres', 'expense', 0, p_tenant_id),
    ('661000', 'Charges d interets', 'expense', 0, p_tenant_id),
    ('661100', 'Interets sur emprunts et dettes', 'expense', 0, p_tenant_id),
    ('661110', 'Interets sur emprunts', 'expense', 0, p_tenant_id),
    ('661120', 'Interets sur dettes financieres', 'expense', 0, p_tenant_id),
    ('661130', 'Interets sur comptes courants et depots crediteurs', 'expense', 0, p_tenant_id),
    ('661160', 'Interets bancaires et sur operations de financement', 'expense', 0, p_tenant_id),
    ('661170', 'Interets sur autres operations de financement', 'expense', 0, p_tenant_id),
    ('661180', 'Interets des obligations', 'expense', 0, p_tenant_id),
    ('661500', 'Interets bancaires et sur operations de financement (escompte)', 'expense', 0, p_tenant_id),
    ('661600', 'Interets sur autres operations de financement', 'expense', 0, p_tenant_id),
    ('661700', 'Interets sur autres operations de financement (autres)', 'expense', 0, p_tenant_id),
    ('661800', 'Interets sur autres operations de financement (autres)', 'expense', 0, p_tenant_id),
    ('662000', 'Pertes de change', 'expense', 0, p_tenant_id),
    ('664000', 'Pertes sur creances liees a des participations', 'expense', 0, p_tenant_id),
    ('665000', 'Escomptes accordes', 'expense', 0, p_tenant_id),
    ('666000', 'Pertes de change', 'expense', 0, p_tenant_id),
    ('667000', 'Charges nettes sur cessions d immobilisations financieres', 'expense', 0, p_tenant_id),
    ('668000', 'Autres charges financieres', 'expense', 0, p_tenant_id),
    ('668100', 'Interets sur obligations', 'expense', 0, p_tenant_id),
    ('668200', 'Interets sur bons de caisse', 'expense', 0, p_tenant_id),
    ('668400', 'Autres charges financieres (autres)', 'expense', 0, p_tenant_id),
    ('668800', 'Frais financiers sur emprunts', 'expense', 0, p_tenant_id),
    ('669000', 'Rabais, remises et ristournes obtenus sur charges financieres', 'expense', 0, p_tenant_id),
    ('670000', 'Charges exceptionnelles', 'expense', 0, p_tenant_id),
    ('671000', 'Charges exceptionnelles sur operations de gestion', 'expense', 0, p_tenant_id),
    ('671100', 'Penalites sur marches', 'expense', 0, p_tenant_id),
    ('671200', 'Penalites, amendes fiscales et penales', 'expense', 0, p_tenant_id),
    ('671300', 'Dons, liberalites', 'expense', 0, p_tenant_id),
    ('671400', 'Subventions accordees', 'expense', 0, p_tenant_id),
    ('671500', 'Rappels d impots (autres que sur le benefice)', 'expense', 0, p_tenant_id),
    ('671700', 'Rappels d impots (sur le benefice)', 'expense', 0, p_tenant_id),
    ('671800', 'Autres charges exceptionnelles', 'expense', 0, p_tenant_id),
    ('672000', 'Charges sur exercices anterieurs', 'expense', 0, p_tenant_id),
    ('672100', 'Charges sur exercices anterieurs (operations de gestion)', 'expense', 0, p_tenant_id),
    ('672200', 'Charges sur exercices anterieurs (operations de capital)', 'expense', 0, p_tenant_id),
    ('675000', 'Valeurs comptables des elements d actif cedes', 'expense', 0, p_tenant_id),
    ('675100', 'Immobilisations incorporelles', 'expense', 0, p_tenant_id),
    ('675200', 'Immobilisations corporelles', 'expense', 0, p_tenant_id),
    ('675300', 'Immobilisations financieres', 'expense', 0, p_tenant_id),
    ('675400', 'Stocks', 'expense', 0, p_tenant_id),
    ('675500', 'Autres elements d actif', 'expense', 0, p_tenant_id),
    ('675600', 'Actions propres', 'expense', 0, p_tenant_id),
    ('675800', 'Autres valeurs comptables des elements d actif cedes', 'expense', 0, p_tenant_id),
    ('676000', 'Pertes de change', 'expense', 0, p_tenant_id),
    ('678000', 'Autres charges exceptionnelles', 'expense', 0, p_tenant_id),
    ('678100', 'Bonis provenant de clauses d indexation', 'expense', 0, p_tenant_id),
    ('678200', 'Malis provenant de clauses d indexation', 'expense', 0, p_tenant_id),
    ('678300', 'Subventions d equilibrage', 'expense', 0, p_tenant_id),
    ('678400', 'Subventions d investissement a reprendre', 'expense', 0, p_tenant_id),
    ('678800', 'Autres charges exceptionnelles (autres)', 'expense', 0, p_tenant_id),
    ('679000', 'Rabais, remises et ristournes obtenus sur charges exceptionnelles', 'expense', 0, p_tenant_id),
    ('680000', 'Dotations aux amortissements et aux provisions', 'expense', 0, p_tenant_id),
    ('681000', 'Dotations aux amortissements et aux provisions - charges d exploitation', 'expense', 0, p_tenant_id),
    ('681100', 'Dotations aux amortissements sur immobilisations incorporelles', 'expense', 0, p_tenant_id),
    ('681110', 'Dotations aux amortissements des frais d etablissement', 'expense', 0, p_tenant_id),
    ('681120', 'Dotations aux amortissements des concessions, brevets, licences, logiciels', 'expense', 0, p_tenant_id),
    ('681150', 'Dotations aux amortissements des fonds commercial', 'expense', 0, p_tenant_id),
    ('681200', 'Dotations aux amortissements sur immobilisations corporelles', 'expense', 0, p_tenant_id),
    ('681210', 'Dotations aux amortissements des terrains', 'expense', 0, p_tenant_id),
    ('681220', 'Dotations aux amortissements des constructions', 'expense', 0, p_tenant_id),
    ('681230', 'Dotations aux amortissements des installations techniques', 'expense', 0, p_tenant_id),
    ('681240', 'Dotations aux amortissements du mobilier', 'expense', 0, p_tenant_id),
    ('681250', 'Dotations aux amortissements du materiel', 'expense', 0, p_tenant_id),
    ('681260', 'Dotations aux amortissements du materiel de transport', 'expense', 0, p_tenant_id),
    ('681700', 'Dotations aux amortissements des immobilisations en cours', 'expense', 0, p_tenant_id),
    ('681500', 'Dotations aux provisions pour risques d exploitation', 'expense', 0, p_tenant_id),
    ('681600', 'Dotations aux provisions pour depreciation des immobilisations incorporelles', 'expense', 0, p_tenant_id),
    ('681610', 'Dotations aux provisions pour depreciation des immobilisations corporelles', 'expense', 0, p_tenant_id),
    ('681620', 'Dotations aux provisions pour depreciation des stocks', 'expense', 0, p_tenant_id),
    ('681630', 'Dotations aux provisions pour depreciation des creances', 'expense', 0, p_tenant_id),
    ('681640', 'Dotations aux provisions pour depreciation des titres de placement', 'expense', 0, p_tenant_id),
    ('681650', 'Dotations aux provisions pour depreciation des autres elements d actif', 'expense', 0, p_tenant_id),
    ('681800', 'Autres dotations aux amortissements et aux provisions', 'expense', 0, p_tenant_id),
    ('681810', 'Dotations aux provisions pour risques et charges d exploitation', 'expense', 0, p_tenant_id),
    ('681820', 'Dotations aux provisions pour depreciation des actifs circulant', 'expense', 0, p_tenant_id),
    ('681830', 'Dotations aux provisions pour depreciation des comptes de tiers', 'expense', 0, p_tenant_id),
    ('681840', 'Dotations aux provisions pour depreciation des comptes financiers', 'expense', 0, p_tenant_id),
    ('681850', 'Dotations aux provisions pour depreciation des autres elements d actif', 'expense', 0, p_tenant_id),
    ('681860', 'Dotations aux provisions pour depreciation des autres elements d actif', 'expense', 0, p_tenant_id),
    ('681870', 'Dotations aux provisions pour depreciation des autres elements d actif', 'expense', 0, p_tenant_id),
    ('681880', 'Dotations aux provisions pour depreciation des autres elements d actif', 'expense', 0, p_tenant_id),
    ('681890', 'Dotations aux provisions pour depreciation des autres elements d actif', 'expense', 0, p_tenant_id),
    ('686000', 'Dotations aux amortissements et aux provisions - charges financieres', 'expense', 0, p_tenant_id),
    ('686100', 'Dotations aux amortissements des immobilisations financieres', 'expense', 0, p_tenant_id),
    ('686500', 'Dotations aux provisions pour risques financiers', 'expense', 0, p_tenant_id),
    ('686600', 'Dotations aux provisions pour depreciation des immobilisations financieres', 'expense', 0, p_tenant_id),
    ('686700', 'Dotations aux provisions pour depreciation des valeurs mobilieres de placement', 'expense', 0, p_tenant_id),
    ('686800', 'Autres dotations aux provisions financieres', 'expense', 0, p_tenant_id),
    ('687000', 'Dotations aux amortissements et aux provisions - charges exceptionnelles', 'expense', 0, p_tenant_id),
    ('687100', 'Dotations aux amortissements exceptionnels des immobilisations', 'expense', 0, p_tenant_id),
    ('687200', 'Dotations aux provisions reglementees (immobilisations)', 'expense', 0, p_tenant_id),
    ('687300', 'Dotations aux provisions reglementees (stocks)', 'expense', 0, p_tenant_id),
    ('687400', 'Dotations aux autres provisions reglementees', 'expense', 0, p_tenant_id),
    ('687500', 'Dotations aux provisions pour risques et charges exceptionnels', 'expense', 0, p_tenant_id),
    ('687600', 'Dotations aux provisions pour depreciation exceptionnelles', 'expense', 0, p_tenant_id),
    ('687700', 'Dotations aux autres provisions exceptionnelles', 'expense', 0, p_tenant_id),
    -- Classe 7 - Produits
    ('700000', 'Ventes de marchandises, production vendue (biens et services)', 'income', 0, p_tenant_id),
    ('701000', 'Ventes de produits finis', 'income', 0, p_tenant_id),
    ('701100', 'Ventes de produits finis (group A)', 'income', 0, p_tenant_id),
    ('701200', 'Ventes de produits finis (group B)', 'income', 0, p_tenant_id),
    ('702000', 'Ventes de produits intermediaires', 'income', 0, p_tenant_id),
    ('702100', 'Ventes de produits intermediaires (group A)', 'income', 0, p_tenant_id),
    ('702200', 'Ventes de produits intermediaires (group B)', 'income', 0, p_tenant_id),
    ('703000', 'Ventes de produits residuels', 'income', 0, p_tenant_id),
    ('704000', 'Travaux', 'income', 0, p_tenant_id),
    ('704100', 'Travaux de construction', 'income', 0, p_tenant_id),
    ('704200', 'Travaux de montage', 'income', 0, p_tenant_id),
    ('705000', 'Etudes', 'income', 0, p_tenant_id),
    ('706000', 'Prestations de services', 'income', 0, p_tenant_id),
    ('706100', 'Prestations de services (group A)', 'income', 0, p_tenant_id),
    ('706200', 'Prestations de services (group B)', 'income', 0, p_tenant_id),
    ('707000', 'Ventes de marchandises', 'income', 0, p_tenant_id),
    ('707100', 'Ventes de marchandises (group A)', 'income', 0, p_tenant_id),
    ('707200', 'Ventes de marchandises (group B)', 'income', 0, p_tenant_id),
    ('708000', 'Produits des activites annexes', 'income', 0, p_tenant_id),
    ('708100', 'Produits des services exploités dans l interet du personnel', 'income', 0, p_tenant_id),
    ('708200', 'Commissions et courtages', 'income', 0, p_tenant_id),
    ('708300', 'Locations diverses', 'income', 0, p_tenant_id),
    ('708400', 'Mise a disposition de personnel', 'income', 0, p_tenant_id),
    ('708500', 'Ports et frais accessoires factures', 'income', 0, p_tenant_id),
    ('708600', 'Bonis sur reprises de emballages consignés', 'income', 0, p_tenant_id),
    ('708800', 'Autres produits d activites annexes', 'income', 0, p_tenant_id),
    ('709000', 'Rabais, remises et ristournes accordes par l entreprise', 'income', 0, p_tenant_id),
    ('709100', 'Rabais, remises et ristournes sur ventes de produits finis', 'income', 0, p_tenant_id),
    ('709600', 'Rabais, remises et ristournes sur prestations de services', 'income', 0, p_tenant_id),
    ('709700', 'Rabais, remises et ristournes sur ventes de marchandises', 'income', 0, p_tenant_id),
    ('709800', 'Rabais, remises et ristournes sur produits des activites annexes', 'income', 0, p_tenant_id),
    ('710000', 'Variation des stocks et production stockee', 'income', 0, p_tenant_id),
    ('713000', 'Variation des stocks (en-cours de production, produits)', 'income', 0, p_tenant_id),
    ('713100', 'Variation des stocks de produits en cours', 'income', 0, p_tenant_id),
    ('713300', 'Variation des stocks de produits', 'income', 0, p_tenant_id),
    ('713400', 'Variation des stocks de services en cours', 'income', 0, p_tenant_id),
    ('713500', 'Variation des stocks de produits finis', 'income', 0, p_tenant_id),
    ('713600', 'Variation des stocks de produits residuels', 'income', 0, p_tenant_id),
    ('713700', 'Variation des stocks de marchandises', 'income', 0, p_tenant_id),
    ('720000', 'Production immobilisee', 'income', 0, p_tenant_id),
    ('721000', 'Production immobilisee - immobilisations incorporelles', 'income', 0, p_tenant_id),
    ('722000', 'Production immobilisee - immobilisations corporelles', 'income', 0, p_tenant_id),
    ('740000', 'Subventions d exploitation', 'income', 0, p_tenant_id),
    ('740100', 'Subventions d exploitation du budget de l Etat', 'income', 0, p_tenant_id),
    ('740200', 'Subventions d exploitation des collectivites locales', 'income', 0, p_tenant_id),
    ('740300', 'Subventions d exploitation des etablissements publics', 'income', 0, p_tenant_id),
    ('740400', 'Subventions d exploitation des entreprises publiques', 'income', 0, p_tenant_id),
    ('740500', 'Subventions d exploitation des autres organismes', 'income', 0, p_tenant_id),
    ('740600', 'Subventions d exploitation des autres organismes (autres)', 'income', 0, p_tenant_id),
    ('740700', 'Subventions d exploitation des autres organismes (autres)', 'income', 0, p_tenant_id),
    ('740800', 'Subventions d exploitation des autres organismes (autres)', 'income', 0, p_tenant_id),
    ('741000', 'Subventions d equilibrage', 'income', 0, p_tenant_id),
    ('748000', 'Autres subventions d exploitation', 'income', 0, p_tenant_id),
    ('750000', 'Autres produits de gestion courante', 'income', 0, p_tenant_id),
    ('751000', 'Redevances pour concessions, brevets, licences, marques, procedes, logiciels', 'income', 0, p_tenant_id),
    ('751100', 'Redevances pour concessions, brevets, licences, marques, procedes, logiciels', 'income', 0, p_tenant_id),
    ('751600', 'Droits d auteur', 'income', 0, p_tenant_id),
    ('751800', 'Autres redevances', 'income', 0, p_tenant_id),
    ('752000', 'Revenus des immeubles non affectes a l exploitation professionnelle', 'income', 0, p_tenant_id),
    ('753000', 'Jetons de presence et remuneration d administrateurs', 'income', 0, p_tenant_id),
    ('754000', 'Quotes-parts de resultat sur operations faites en commun', 'income', 0, p_tenant_id),
    ('754100', 'Quotes-parts de perte', 'income', 0, p_tenant_id),
    ('754200', 'Quotes-parts de benefice', 'income', 0, p_tenant_id),
    ('755000', 'Quotes-parts de perte sur operations faites en commun', 'income', 0, p_tenant_id),
    ('756000', 'Gains de change', 'income', 0, p_tenant_id),
    ('756100', 'Gains de change (autres)', 'income', 0, p_tenant_id),
    ('756600', 'Gains de change (autres)', 'income', 0, p_tenant_id),
    ('756800', 'Ecarts de conversion - passif', 'income', 0, p_tenant_id),
    ('757000', 'Produits de gestion courante (autres)', 'income', 0, p_tenant_id),
    ('758000', 'Produits divers de gestion courante', 'income', 0, p_tenant_id),
    ('758100', 'Gains sur operations a terme', 'income', 0, p_tenant_id),
    ('758200', 'Gains sur operations de change a terme', 'income', 0, p_tenant_id),
    ('758600', 'Autres produits divers de gestion courante', 'income', 0, p_tenant_id),
    ('758800', 'Rabais, remises et ristournes obtenus sur autres produits de gestion courante', 'income', 0, p_tenant_id),
    ('760000', 'Produits financiers', 'income', 0, p_tenant_id),
    ('761000', 'Produits de participations', 'income', 0, p_tenant_id),
    ('761100', 'Revenus des titres de participation', 'income', 0, p_tenant_id),
    ('761600', 'Revenus sur autres formes de participation', 'income', 0, p_tenant_id),
    ('761700', 'Quotes-parts de resultat sur operations faites en commun', 'income', 0, p_tenant_id),
    ('761800', 'Revenus des creances rattachees a des participations', 'income', 0, p_tenant_id),
    ('762000', 'Produits des autres immobilisations financieres', 'income', 0, p_tenant_id),
    ('762100', 'Revenus des titres immobilises', 'income', 0, p_tenant_id),
    ('762600', 'Revenus des pretes', 'income', 0, p_tenant_id),
    ('762700', 'Revenus des creances commerciales', 'income', 0, p_tenant_id),
    ('763000', 'Revenus des autres creances', 'income', 0, p_tenant_id),
    ('763100', 'Revenus des creances commerciales', 'income', 0, p_tenant_id),
    ('763200', 'Revenus des creances diverses', 'income', 0, p_tenant_id),
    ('764000', 'Revenus des valeurs mobilieres de placement', 'income', 0, p_tenant_id),
    ('764100', 'Revenus des actions', 'income', 0, p_tenant_id),
    ('764200', 'Revenus des obligations', 'income', 0, p_tenant_id),
    ('764300', 'Revenus des bons de caisse et du Tresor', 'income', 0, p_tenant_id),
    ('764400', 'Revenus des autres valeurs mobilieres de placement', 'income', 0, p_tenant_id),
    ('765000', 'Escomptes obtenus', 'income', 0, p_tenant_id),
    ('766000', 'Gains de change', 'income', 0, p_tenant_id),
    ('767000', 'Produits nets sur cessions d immobilisations financieres', 'income', 0, p_tenant_id),
    ('768000', 'Autres produits financiers', 'income', 0, p_tenant_id),
    ('768100', 'Interets sur obligations', 'income', 0, p_tenant_id),
    ('768200', 'Interets sur bons de caisse', 'income', 0, p_tenant_id),
    ('768400', 'Autres produits financiers (autres)', 'income', 0, p_tenant_id),
    ('768800', 'Produits des operations de financement', 'income', 0, p_tenant_id),
    ('769000', 'Rabais, remises et ristournes obtenus sur produits financiers', 'income', 0, p_tenant_id),
    ('770000', 'Produits exceptionnels', 'income', 0, p_tenant_id),
    ('771000', 'Produits exceptionnels sur operations de gestion', 'income', 0, p_tenant_id),
    ('771100', 'Dedommagements recus', 'income', 0, p_tenant_id),
    ('771200', 'Dégrèvements d impots', 'income', 0, p_tenant_id),
    ('771300', 'Liberalites recues', 'income', 0, p_tenant_id),
    ('771400', 'Subventions d equilibrage', 'income', 0, p_tenant_id),
    ('771500', 'Subventions d investissement', 'income', 0, p_tenant_id),
    ('771700', 'Rentrées sur creances amorties', 'income', 0, p_tenant_id),
    ('771800', 'Autres produits exceptionnels', 'income', 0, p_tenant_id),
    ('772000', 'Produits sur exercices anterieurs', 'income', 0, p_tenant_id),
    ('772100', 'Produits sur exercices anterieurs (operations de gestion)', 'income', 0, p_tenant_id),
    ('772200', 'Produits sur exercices anterieurs (operations de capital)', 'income', 0, p_tenant_id),
    ('775000', 'Produits des cessions d elements d actif', 'income', 0, p_tenant_id),
    ('775100', 'Immobilisations incorporelles', 'income', 0, p_tenant_id),
    ('775200', 'Immobilisations corporelles', 'income', 0, p_tenant_id),
    ('775300', 'Immobilisations financieres', 'income', 0, p_tenant_id),
    ('775400', 'Stocks', 'income', 0, p_tenant_id),
    ('775500', 'Autres elements d actif', 'income', 0, p_tenant_id),
    ('775600', 'Actions propres', 'income', 0, p_tenant_id),
    ('775800', 'Autres produits des cessions d elements d actif', 'income', 0, p_tenant_id),
    ('776000', 'Gains de change', 'income', 0, p_tenant_id),
    ('777000', 'Quotes-parts des subventions d investissement inscrites au resultat de l exercice', 'income', 0, p_tenant_id),
    ('778000', 'Autres produits exceptionnels', 'income', 0, p_tenant_id),
    ('778100', 'Bonis provenant de clauses d indexation', 'income', 0, p_tenant_id),
    ('778200', 'Malis provenant de clauses d indexation', 'income', 0, p_tenant_id),
    ('778300', 'Subventions d equilibrage', 'income', 0, p_tenant_id),
    ('778400', 'Subventions d investissement a reprendre', 'income', 0, p_tenant_id),
    ('778800', 'Autres produits exceptionnels (autres)', 'income', 0, p_tenant_id),
    ('779000', 'Rabais, remises et ristournes accordes sur produits exceptionnels', 'income', 0, p_tenant_id),
    ('780000', 'Reprises sur amortissements et provisions', 'income', 0, p_tenant_id),
    ('781000', 'Reprises sur amortissements et provisions - charges d exploitation', 'income', 0, p_tenant_id),
    ('781100', 'Reprises sur amortissements des immobilisations incorporelles', 'income', 0, p_tenant_id),
    ('781200', 'Reprises sur amortissements des immobilisations corporelles', 'income', 0, p_tenant_id),
    ('781500', 'Reprises sur provisions pour risques d exploitation', 'income', 0, p_tenant_id),
    ('781600', 'Reprises sur provisions pour depreciation des immobilisations incorporelles', 'income', 0, p_tenant_id),
    ('781610', 'Reprises sur provisions pour depreciation des immobilisations corporelles', 'income', 0, p_tenant_id),
    ('781620', 'Reprises sur provisions pour depreciation des stocks', 'income', 0, p_tenant_id),
    ('781630', 'Reprises sur provisions pour depreciation des creances', 'income', 0, p_tenant_id),
    ('781640', 'Reprises sur provisions pour depreciation des titres de placement', 'income', 0, p_tenant_id),
    ('781700', 'Reprises sur provisions pour depreciation des autres elements d actif', 'income', 0, p_tenant_id),
    ('781800', 'Autres reprises sur amortissements et provisions', 'income', 0, p_tenant_id),
    ('786000', 'Reprises sur amortissements et provisions - charges financieres', 'income', 0, p_tenant_id),
    ('786100', 'Reprises sur amortissements des immobilisations financieres', 'income', 0, p_tenant_id),
    ('786500', 'Reprises sur provisions pour risques financiers', 'income', 0, p_tenant_id),
    ('786600', 'Reprises sur provisions pour depreciation des immobilisations financieres', 'income', 0, p_tenant_id),
    ('786700', 'Reprises sur provisions pour depreciation des valeurs mobilieres de placement', 'income', 0, p_tenant_id),
    ('786800', 'Autres reprises sur provisions financieres', 'income', 0, p_tenant_id),
    ('787000', 'Reprises sur amortissements et provisions - charges exceptionnelles', 'income', 0, p_tenant_id),
    ('787100', 'Reprises sur amortissements exceptionnels des immobilisations', 'income', 0, p_tenant_id),
    ('787200', 'Reprises sur provisions reglementees (immobilisations)', 'income', 0, p_tenant_id),
    ('787300', 'Reprises sur provisions reglementees (stocks)', 'income', 0, p_tenant_id),
    ('787400', 'Reprises sur autres provisions reglementees', 'income', 0, p_tenant_id),
    ('787500', 'Reprises sur provisions pour risques et charges exceptionnels', 'income', 0, p_tenant_id),
    ('787600', 'Reprises sur provisions pour depreciation exceptionnelles', 'income', 0, p_tenant_id),
    ('787700', 'Reprises sur autres provisions exceptionnelles', 'income', 0, p_tenant_id),
    ('790000', 'Transferts de charges', 'income', 0, p_tenant_id),
    ('791000', 'Transferts de charges d exploitation', 'income', 0, p_tenant_id),
    ('796000', 'Transferts de charges financieres', 'income', 0, p_tenant_id),
    ('797000', 'Transferts de charges exceptionnelles', 'income', 0, p_tenant_id),
    -- Classe 8 - Comptes speciaux
    ('800000', 'Engagements financiers', 'liability', 0, p_tenant_id),
    ('801000', 'Engagements de garantie', 'liability', 0, p_tenant_id),
    ('801100', 'Avals, cautions, garanties', 'liability', 0, p_tenant_id),
    ('801400', 'Credits de signature par endossement', 'liability', 0, p_tenant_id),
    ('801700', 'Hypotèques', 'liability', 0, p_tenant_id),
    ('801800', 'Gages sur stocks', 'liability', 0, p_tenant_id),
    ('804000', 'Engagements financiers recus', 'asset', 0, p_tenant_id),
    ('804100', 'Avals, cautions, garanties recus', 'asset', 0, p_tenant_id),
    ('804400', 'Credits de signature par endossement recus', 'asset', 0, p_tenant_id),
    ('804500', 'Hypotèques recues', 'asset', 0, p_tenant_id),
    ('804800', 'Gages sur stocks recus', 'asset', 0, p_tenant_id),
    ('808000', 'Engagements divers', 'liability', 0, p_tenant_id),
    ('808100', 'Engagements divers donnes', 'liability', 0, p_tenant_id),
    ('808400', 'Engagements divers recus', 'asset', 0, p_tenant_id)
  ON CONFLICT (tenant_id, code) DO NOTHING;
END;
$$;

GRANT EXECUTE ON FUNCTION seed_standard_chart(uuid) TO authenticated;

-- ============================================
-- 2. PATCH bootstrap_tenant() TO CALL seed_standard_chart()
-- ============================================
CREATE OR REPLACE FUNCTION bootstrap_tenant(p_tenant_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_tenant record;
  v_year int := EXTRACT(YEAR FROM CURRENT_DATE)::int;
  v_fy_id uuid;
  v_month int;
  v_period_start date;
  v_period_end date;
  v_labels text[] := ARRAY['Janvier','Fevrier','Mars','Avril','Mai','Juin','Juillet','Aout','Septembre','Octobre','Novembre','Decembre'];
BEGIN
  SELECT * INTO v_tenant FROM tenants WHERE id = p_tenant_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tenant % not found', p_tenant_id;
  END IF;

  -- 1. CHART OF ACCOUNTS — seed directly via seed_standard_chart()
  IF NOT EXISTS (SELECT 1 FROM chart_accounts WHERE tenant_id = p_tenant_id) THEN
    PERFORM seed_standard_chart(p_tenant_id);
  END IF;

  -- 2. STANDARD JOURNALS
  INSERT INTO journals (code, name, type, account_counterpart, status, locked, tenant_id)
  VALUES
    ('VT', 'Journal des ventes',        'sale',     '411000', 'active', false, p_tenant_id),
    ('AC', 'Journal des achats',        'purchase', '401000', 'active', false, p_tenant_id),
    ('BQ', 'Journal de banque',         'bank',     '512000', 'active', false, p_tenant_id),
    ('CA', 'Journal de caisse',         'cash',     '530000', 'active', false, p_tenant_id),
    ('OD', 'Operations diverses',       'general',  NULL,     'active', false, p_tenant_id),
    ('AN', 'A-nouveaux',                'general',  NULL,     'active', false, p_tenant_id)
  ON CONFLICT (tenant_id, code) DO NOTHING;

  -- 3. DEFAULT CURRENCIES
  INSERT INTO currencies (code, name, symbol, exchange_rate, tenant_id)
  VALUES
    ('EUR', 'Euro',            '€', 1.0,    p_tenant_id),
    ('USD', 'Dollar US',       '$', 1.08,   p_tenant_id),
    ('GBP', 'Livre Sterling',  '£', 0.85,   p_tenant_id)
  ON CONFLICT (tenant_id, code) DO NOTHING;

  -- 4. FISCAL YEAR + 12 MONTHLY PERIODS (current year)
  IF NOT EXISTS (SELECT 1 FROM fiscal_years WHERE tenant_id = p_tenant_id AND code = 'FY' || v_year) THEN
    INSERT INTO fiscal_years (code, start_date, end_date, status, tenant_id)
    VALUES ('FY' || v_year, make_date(v_year, 1, 1), make_date(v_year, 12, 31), 'open', p_tenant_id)
    RETURNING id INTO v_fy_id;

    FOR v_month IN 1 .. 12 LOOP
      v_period_start := make_date(v_year, v_month, 1);
      v_period_end := (v_period_start + INTERVAL '1 month - 1 day')::date;
      INSERT INTO fiscal_periods (fiscal_year_id, period_number, period_label, start_date, end_date, status, tenant_id)
      VALUES (v_fy_id, v_month, v_labels[v_month] || ' ' || v_year, v_period_start, v_period_end, 'open', p_tenant_id);
    END LOOP;
  END IF;

  -- 5. COMPANY SETTINGS
  IF NOT EXISTS (SELECT 1 FROM company_settings WHERE tenant_id = p_tenant_id) THEN
    INSERT INTO company_settings (name, legal_name, vat_number, siret, address, city, postal_code, country, currency, fiscal_year_start, tenant_id)
    VALUES (
      v_tenant.name,
      COALESCE(v_tenant.legal_name, v_tenant.name),
      v_tenant.vat_number,
      v_tenant.siret,
      v_tenant.address,
      v_tenant.city,
      v_tenant.postal_code,
      COALESCE(v_tenant.country, 'France'),
      COALESCE(v_tenant.currency, 'EUR'),
      '01-01',
      p_tenant_id
    );
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION bootstrap_tenant(uuid) TO authenticated;

-- ============================================
-- 3. BACKFILL EXISTING TENANTS MISSING CHART
-- ============================================
DO $$
DECLARE
  t record;
  v_count int;
BEGIN
  FOR t IN SELECT id FROM tenants LOOP
    SELECT count(*) INTO v_count FROM chart_accounts WHERE tenant_id = t.id;
    IF v_count = 0 THEN
      RAISE NOTICE 'Backfilling chart for tenant %', t.id;
      PERFORM seed_standard_chart(t.id);
    ELSE
      RAISE NOTICE 'Tenant % already has % chart accounts, skipping', t.id, v_count;
    END IF;
  END LOOP;
END $$;

-- ============================================
-- DONE
-- ============================================
-- New tenants will now get the full French PCG automatically
-- via bootstrap_tenant() -> seed_standard_chart().
-- Existing tenants have been backfilled above.
-- ============================================
