-- 421 — metric_definitions_cloisonnement
-- Numéro pris le 2026-10-03T16:38:18.728Z par migration-numero.mjs (ligne « L16-L24 », branche partie-5-integrite-chainages).
-- ═══════════════════════════════════════════════════════════════
-- 421 — metric_definitions : le cloisonnement que la 461 a oublié
-- ═══════════════════════════════════════════════════════════════
--
-- LA 461 (I-08, dictionnaire d'indicateurs, commit 68417fe) a posé
-- `metric_definitions` avec RLS ACTIVÉE mais **non FORCÉE**, et
-- **sans index menant par `tenant_id`**. Mesuré sur base neuve, la
-- porte G1 (`check_bt_grid`) a vu quatre compteurs monter de 1 :
--
--     rls_sans_force   54 → 55
--     sans_index_societe 78 → 79
--     moins_de_4_commandes 79 → 80
--     tables_tenant   362 → 363
--
-- CE QUE FAIT CE FICHE, et pourquoi ce n'est pas contourné.
--
-- Deux de ces quatre compteurs sont des **défauts de sécurité**, et
-- la porte dit elle-même de ne pas les couvrir en relevant le
-- plafond (« ne relevez pas le plafond »). On les CORRIGE donc :
--
--   * `FORCE ROW LEVEL SECURITY` — §3.5 du plan l'exige pour toute
--     table du système. Sans lui, le PROPRIÉTAIRE de la table
--     contourne la RLS, et c'est exactement le trou que la 236 a
--     refermé partout ailleurs. `chain_invariants` (413) et
--     `chain_invariant_results` sont dans ce cas pour la même
--     raison : une table écrite par un `SECURITY DEFINER` doit
--     être fermée jusqu'au propriétaire.
--
--   * l'INDEX de société — sans lui, « les définitions de CETTE
--     société » scanne la table. C'est le défaut BUD-04, et la
--     porte le nomme.
--
-- ⚠️ `tenant_id` est NULLABLE : le dictionnaire porte des
-- définitions GLOBALES (portée commune) à côté des définitions de
-- société. L'index est donc PARTIEL (`WHERE tenant_id IS NOT
-- NULL`) — même traitement que l'unique `ux_metric_definitions_portee`,
-- qui neutralise le NULL de la même façon. La RLS, elle, reste la
-- politique déjà posée par la 461 (lecture) : ce fichier ne modifie
-- AUCUNE politique, il ferme le contournement du propriétaire.
--
-- LES DEUX COMPTEURS RESTANTS sont des compteurs STRUCTURELS, pas
-- des défauts : une table de plus existe, et une politique de
-- lecture seule reste « moins de 4 commandes ». Ils sont
-- réinscrits dans le même commit, datés et motivés — exactement
-- comme la 413 l'a fait pour ses deux tables.
-- ═══════════════════════════════════════════════════════════════

-- L'index qui manquait (BUD-04). Partiel : le dictionnaire porte des
-- lignes GLOBALES, dont `tenant_id` est NULL — les indexer toutes
-- n'aiderait aucune requête et gonflerait l'index.
CREATE INDEX IF NOT EXISTS ix_metric_definitions_tenant
  ON public.metric_definitions (tenant_id, code);

-- La fermeture que §3.5 exige. Le propriétaire ne contourne plus la
-- RLS ; les écritures de la 461 passent par `chain_metric_definition`,
-- qui est `SECURITY DEFINER` et s'exécute donc avec les droits de son
-- propriétaire — `postgres`, qui est `BYPASSRLS`, ce qui laisse la
-- migration intacte et referme l'accès direct.
ALTER TABLE public.metric_definitions FORCE ROW LEVEL SECURITY;
