import {
  BookOpen,
  ShoppingCart,
  Wallet,
  Boxes,
  Factory,
  Users,
  BarChart3,
  PieChart,
  ClipboardList,
  Settings,
  Home,
  type LucideIcon,
} from 'lucide-react'

// ============================================
// TYPES
// ============================================
export type ModuleColor = 'blue' | 'indigo' | 'emerald' | 'amber' | 'violet' | 'rose' | 'cyan' | 'teal' | 'fuchsia' | 'slate' | 'lime'

export interface NavItem {
  labelKey: string
  path: string
}

export interface NavSection {
  subGroupKey?: string
  hubPath?: string
  items: NavItem[]
}

export interface NavModule {
  id: string
  groupKey: string
  color: ModuleColor
  icon: LucideIcon
  path: string
  homePath?: string
  sections?: NavSection[]
  items?: NavItem[]
}

// ============================================
// NAVIGATION CONFIG
// ============================================
export const navModules: NavModule[] = [
  {
    id: 'home',
    groupKey: 'groups.home',
    color: 'blue',
    icon: Home,
    path: '/home',
    homePath: '/home',
    items: [
      { labelKey: 'items.dashboard', path: '/dashboard' },
      { labelKey: 'items.myWorkspace', path: '/dashboard/workspace' },
    ],
  },
  {
    id: 'accounting',
    groupKey: 'groups.accounting',
    color: 'indigo',
    icon: BookOpen,
    path: '/accounting',
    homePath: '/accounting/home',
    sections: [
      {
        subGroupKey: 'subGroups.structure',
        hubPath: '/accounting/structure',
        items: [
          { labelKey: 'items.accountingHome', path: '/accounting/home' },
          { labelKey: 'items.chartAccounts', path: '/accounting/chart-accounts' },
          { labelKey: 'items.thirdParty', path: '/accounting/third-party' },
          { labelKey: 'items.paymentGeneration', path: '/accounting/payment-generation' },
          { labelKey: 'items.journals', path: '/accounting/journals' },
          { labelKey: 'items.entryTemplates', path: '/accounting/entry-templates' },
          { labelKey: 'items.fiscalYears', path: '/system/fiscal-years' },
          { labelKey: 'items.analyticSections', path: '/accounting/structure/analytic' },
          { labelKey: 'items.budgets', path: '/accounting/structure/budgets' },
          { labelKey: 'items.budgetCommitments', path: '/accounting/structure/budget-commitments' },
          { labelKey: 'items.analyticPlans', path: '/accounting/structure/analytic-plans' },
          { labelKey: 'items.distributionGrills', path: '/accounting/structure/distribution-grills' },
          { labelKey: 'items.banks', path: '/banking/accounts' },
          { labelKey: 'items.fixedAssets', path: '/accounting/fixed-assets' },
          { labelKey: 'items.assetDepreciationPlans', path: '/accounting/asset-depreciation-plans' },
          { labelKey: 'items.assetFamilies', path: '/accounting/asset-families' },
          { labelKey: 'items.assetRevaluations', path: '/accounting/asset-revaluations' },
          { labelKey: 'items.assetBatchDisposals', path: '/accounting/asset-batch-disposals' },
          { labelKey: 'items.assetFromEntry', path: '/accounting/asset-from-entry' },
          { labelKey: 'items.taxRates', path: '/accounting/tax-rates' },
          { labelKey: 'items.fiscalPositions', path: '/accounting/fiscal-positions' },
          { labelKey: 'items.accountTags', path: '/accounting/account-tags' },
          { labelKey: 'items.paymentTerms', path: '/accounting/payment-terms' },
          { labelKey: 'items.bankSync', path: '/banking/sync' },
          { labelKey: 'items.exchangeGainLoss', path: '/banking/exchange-gain-loss' },
          { labelKey: 'items.checkBooks', path: '/banking/check-books' },
          { labelKey: 'items.partnerCategories', path: '/accounting/partner-categories' },
        ],
      },
      {
        subGroupKey: 'subGroups.processing',
        hubPath: '/accounting/traitement',
        items: [
          { labelKey: 'items.journalEntry', path: '/accounting/treatment/journal-entry' },
          { labelKey: 'items.lettrage', path: '/accounting/treatment/lettrage' },
          { labelKey: 'items.searchEntries', path: '/accounting/treatment/search' },
          { labelKey: 'items.journalClosure', path: '/accounting/treatment/journal-closure' },
          { labelKey: 'items.fiscalYearClosure', path: '/accounting/treatment/fiscal-year-closure' },
          { labelKey: 'items.bankReconciliation', path: '/banking/reconciliation' },
          { labelKey: 'items.bankReconciliationState', path: '/banking/reconciliation-state' },
          { labelKey: 'items.bankReconciliationPdf', path: '/banking/reconciliation-pdf' },
          { labelKey: 'items.bankTransactions', path: '/banking/transactions' },
          { labelKey: 'items.bankRules', path: '/banking/rules' },
          { labelKey: 'items.recurringEntries', path: '/accounting/treatment/recurring-entries' },
          { labelKey: 'items.regularization', path: '/accounting/treatment/regularization' },
          { labelKey: 'items.paymentReminders', path: '/accounting/treatment/payment-reminders' },
          { labelKey: 'items.bankReconRules', path: '/accounting/treatment/bank-reconciliation-rules' },
          { labelKey: 'items.bankStatementImport', path: '/accounting/treatment/bank-statement-import' },
          { labelKey: 'items.ediTva', path: '/accounting/treatment/edi-tva' },
          { labelKey: 'items.batchEntry', path: '/accounting/batch-entry' },
          { labelKey: 'items.autoLabels', path: '/accounting/auto-labels' },
          { labelKey: 'items.extourne', path: '/accounting/extourne' },
          { labelKey: 'items.carryForward', path: '/accounting/carry-forward' },
          { labelKey: 'items.lettrageDifferences', path: '/accounting/lettrage-differences' },
          { labelKey: 'items.accountingControls', path: '/accounting/controls' },
          { labelKey: 'items.cashControl', path: '/accounting/cash-control' },
          { labelKey: 'items.fecAttestations', path: '/accounting/fec-attestations' },
          { labelKey: 'items.tierRibs', path: '/accounting/tier-ribs' },
          { labelKey: 'items.ifrsAdjustments', path: '/accounting/ifrs-adjustments' },
          { labelKey: 'items.taxPayments', path: '/accounting/tax-payments' },
          { labelKey: 'items.deferredPrinting', path: '/accounting/deferred-printing' },
          { labelKey: 'items.journalAccessRights', path: '/accounting/journal-access-rights' },
          { labelKey: 'items.vatOnCollections', path: '/accounting/vat-on-collections' },
          { labelKey: 'items.saisieParPiece', path: '/accounting/treatment/saisie-par-piece' },
        ],
      },
      {
        subGroupKey: 'subGroups.states',
        hubPath: '/accounting/etats',
        items: [
          { labelKey: 'items.generalLedger', path: '/accounting/general-ledger' },
          { labelKey: 'items.generalLedgerTiers', path: '/accounting/states/general-ledger-tiers' },
          { labelKey: 'items.trialBalance', path: '/accounting/trial-balance' },
          { labelKey: 'items.brouillard', path: '/accounting/states/brouillard' },
          { labelKey: 'items.agedBalance', path: '/accounting/states/aged-balance' },
          { labelKey: 'items.echeancier', path: '/accounting/states/echeancier' },
          { labelKey: 'items.sig', path: '/accounting/states/sig' },
          { labelKey: 'items.analyticBalance', path: '/accounting/states/analytic-balance' },
          { labelKey: 'items.fecExport', path: '/accounting/states/fec' },
          { labelKey: 'items.paymentDelay', path: '/accounting/reports/payment-delay' },
          { labelKey: 'items.currencyRevaluation', path: '/accounting/reports/currency-revaluation' },
          { labelKey: 'items.tvs', path: '/accounting/reports/tvs' },
          { labelKey: 'items.progressiveBalance', path: '/accounting/reports/progressive-balance' },
          { labelKey: 'items.fiscalBackup', path: '/accounting/reports/fiscal-backup' },
          { labelKey: 'items.liasseFiscale', path: '/accounting/liasse-fiscale' },
          { labelKey: 'items.accountantPortal', path: '/accounting/accountant-portal' },
          { labelKey: 'items.profitLoss', path: '/reports/profit-loss' },
          { labelKey: 'items.balanceSheet', path: '/reports/balance-sheet' },
          { labelKey: 'items.cashFlow', path: '/reports/cash-flow' },
          { labelKey: 'items.vat', path: '/reports/vat' },
          { labelKey: 'items.journalsReport', path: '/reports/journals' },
          { labelKey: 'items.justificatifSolde', path: '/accounting/justificatif-solde' },
          { labelKey: 'items.etatRapprochement', path: '/accounting/etat-rapprochement' },
          { labelKey: 'items.reminderLevels', path: '/accounting/reminder-levels' },
          { labelKey: 'items.revisionCycles', path: '/accounting/revision-cycles' },
          { labelKey: 'items.fusionComptes', path: '/accounting/fusion-comptes' },
          { labelKey: 'items.reportingPlans', path: '/accounting/reporting-plans' },
          { labelKey: 'items.compaction', path: '/accounting/compaction' },
          { labelKey: 'items.rgpd', path: '/accounting/rgpd' },
          { labelKey: 'items.corporateTax', path: '/accounting/corporate-tax-calc' },
          { labelKey: 'items.customReports', path: '/accounting/custom-reports' },
          { labelKey: 'items.gridTemplates', path: '/accounting/grid-templates' },
          { labelKey: 'items.standardLabels', path: '/accounting/standard-labels' },
          { labelKey: 'items.analyticJournalCodes', path: '/accounting/analytic-journal-codes' },
          { labelKey: 'items.analyticODEntry', path: '/accounting/analytic-od-entry' },
          { labelKey: 'items.thirdPartyInquiry', path: '/accounting/third-party-inquiry' },
          { labelKey: 'items.analyticInquiry', path: '/accounting/analytic-inquiry' },
          { labelKey: 'items.reimputation', path: '/accounting/reimputation' },
        ],
      },
    ],
  },
  {
    id: 'commercial',
    groupKey: 'groups.commercial',
    color: 'emerald',
    icon: ShoppingCart,
    path: '/commercial',
    homePath: '/commercial/home',
    sections: [
      {
        subGroupKey: 'subGroups.sales',
        hubPath: '/sales',
        items: [
          { labelKey: 'items.customers', path: '/sales/customers' },
          { labelKey: 'items.invoices', path: '/sales/invoices' },
          { labelKey: 'items.quotes', path: '/sales/quotes' },
          { labelKey: 'items.creditNotes', path: '/sales/credits' },
          { labelKey: 'items.recurringInvoices', path: '/sales/recurring' },
          { labelKey: 'items.salesOrders', path: '/sales/orders' },
          { labelKey: 'items.deliveryNotes', path: '/sales/delivery-notes' },
          { labelKey: 'items.customerPayments', path: '/sales/payments' },
          { labelKey: 'items.eInvoice', path: '/sales/e-invoice' },
          { labelKey: 'items.prospects', path: '/commercial/prospects' },
          { labelKey: 'items.representatives', path: '/commercial/representatives' },
          { labelKey: 'items.deliverySchedules', path: '/commercial/delivery-schedules' },
          { labelKey: 'items.creditControl', path: '/sales/credit-control' },
          { labelKey: 'items.promotions', path: '/sales/promotions' },
          { labelKey: 'items.revenueSimulation', path: '/sales/simulation' },
          { labelKey: 'items.marginAnalysis', path: '/sales/margins' },
          { labelKey: 'items.opportunities', path: '/crm/opportunities' },
          { labelKey: 'items.crmActivities', path: '/crm/activities' },
          { labelKey: 'items.crmCampaigns', path: '/crm/campaigns' },
          { labelKey: 'items.territories', path: '/crm/territories' },
          { labelKey: 'items.salesForecasts', path: '/crm/forecasts' },
          { labelKey: 'items.tickets', path: '/crm/tickets' },
          { labelKey: 'items.serviceContracts', path: '/crm/contracts' },
          { labelKey: 'items.crmKnowledgeBase', path: '/crm/knowledge-base' },
          { labelKey: 'items.posTerminal', path: '/pos/terminal' },
          { labelKey: 'items.posSessions', path: '/pos/sessions' },
          { labelKey: 'items.posStats', path: '/pos/stats' },
          { labelKey: 'items.posPaymentMethods', path: '/pos/payment-methods' },
        ],
      },
      {
        subGroupKey: 'subGroups.purchases',
        hubPath: '/purchases',
        items: [
          { labelKey: 'items.suppliers', path: '/purchases/suppliers' },
          { labelKey: 'items.purchaseInvoices', path: '/purchases/invoices' },
          { labelKey: 'items.supplierCreditNotes', path: '/purchases/credits' },
          { labelKey: 'items.productsServices', path: '/purchases/products' },
          { labelKey: 'items.invoiceAutomation', path: '/purchases/automation' },
          { labelKey: 'items.purchaseOrders', path: '/purchases/orders' },
          { labelKey: 'items.goodsReceipts', path: '/purchases/goods-receipts' },
          { labelKey: 'items.supplierPayments', path: '/purchases/payments' },
          { labelKey: 'items.purchaseApproval', path: '/purchases/approval' },
          { labelKey: 'items.purchaseRequests', path: '/purchases/requests' },
          { labelKey: 'items.supplierPriceLists', path: '/purchases/supplier-price-lists' },
          { labelKey: 'items.supplierDeliverySchedules', path: '/purchases/delivery-schedules' },
        ],
      },
    ],
  },
  {
    id: 'treasury',
    groupKey: 'groups.treasury',
    color: 'amber',
    icon: Wallet,
    path: '/treasury',
    homePath: '/treasury/home',
    items: [
      { labelKey: 'items.treasuryDashboard', path: '/treasury/dashboard' },
      { labelKey: 'items.forecasts', path: '/treasury/forecast' },
      { labelKey: 'items.paymentOrders', path: '/treasury/payment-orders' },
      { labelKey: 'items.sepaTransfers', path: '/treasury/sepa' },
      { labelKey: 'items.collections', path: '/treasury/collections' },
      { labelKey: 'items.mcf', path: '/treasury/mcf' },
      { labelKey: 'items.treasuryTransfers', path: '/treasury/transfers' },
      { labelKey: 'items.creditLines', path: '/treasury/credit-lines' },
      { labelKey: 'items.investments', path: '/treasury/investments' },
      { labelKey: 'items.valueDates', path: '/treasury/value-dates' },
      { labelKey: 'items.treasuryRecurring', path: '/treasury/recurring' },
      { labelKey: 'items.consolidatedTreasury', path: '/treasury/consolidated' },
    ],
  },
  {
    id: 'stock',
    groupKey: 'groups.stock',
    color: 'violet',
    icon: Boxes,
    path: '/stock',
    homePath: '/stock/home',
    items: [
      { labelKey: 'items.stockQuantities', path: '/stock/quantities' },
      { labelKey: 'items.stockMovements', path: '/stock/movements' },
      { labelKey: 'items.warehouses', path: '/stock/warehouses' },
      { labelKey: 'items.inventory', path: '/stock/inventory' },
      { labelKey: 'items.reorder', path: '/stock/reorder' },
      { labelKey: 'items.priceLists', path: '/stock/price-lists' },
      { labelKey: 'items.gescomTransfer', path: '/stock/transfer' },
      { labelKey: 'items.bom', path: '/stock/boms' },
      { labelKey: 'items.manufacturingOrders', path: '/stock/manufacturing' },
      { labelKey: 'items.warehouseLocations', path: '/stock/warehouse-locations' },
      { labelKey: 'items.qualityChecks', path: '/stock/quality-checks' },
      { labelKey: 'items.pickLists', path: '/stock/pick-lists' },
      { labelKey: 'items.serialNumbers', path: '/stock/serial-numbers' },
      { labelKey: 'items.productBatches', path: '/stock/product-batches' },
      { labelKey: 'items.productSubstitutes', path: '/stock/product-substitutes' },
      { labelKey: 'items.dormantStock', path: '/stock/dormant-stock' },
      { labelKey: 'items.productGrids', path: '/stock/product-grids' },
      { labelKey: 'items.stockAlerts', path: '/stock/alerts' },
      { labelKey: 'items.stockReservations', path: '/stock/reservations' },
      { labelKey: 'items.lotTraceability', path: '/stock/traceability' },
    ],
  },
  {
    id: 'production',
    groupKey: 'groups.production',
    color: 'lime',
    icon: Factory,
    path: '/production',
    homePath: '/production/home',
    sections: [
      {
        subGroupKey: 'subGroups.manufacturing',
        hubPath: '/production/manufacturing',
        items: [
          { labelKey: 'items.productionDashboard', path: '/production' },
          { labelKey: 'items.routings', path: '/production/routings' },
          { labelKey: 'items.machines', path: '/production/machines' },
          { labelKey: 'items.toolings', path: '/production/toolings' },
          { labelKey: 'items.manufacturingOrders', path: '/production/manufacturing' },
        ],
      },
      {
        subGroupKey: 'subGroups.subcontracting',
        hubPath: '/production/subcontracting',
        items: [
          { labelKey: 'items.subcontracting', path: '/production/subcontracting/orders' },
          { labelKey: 'items.subcontractingShipments', path: '/production/subcontracting/shipments' },
          { labelKey: 'items.subcontractingReceipts', path: '/production/subcontracting/receipts' },
          { labelKey: 'items.subcontractingSupervisor', path: '/production/subcontracting/supervisor' },
        ],
      },
      {
        subGroupKey: 'subGroups.planning',
        hubPath: '/production/planning',
        items: [
          { labelKey: 'items.mrp', path: '/production/mrp' },
          { labelKey: 'items.pendingDocs', path: '/production/mrp/pending' },
          { labelKey: 'items.forecasts', path: '/production/forecasts' },
          { labelKey: 'items.planning', path: '/production/planning' },
          { labelKey: 'items.workflows', path: '/production/workflows' },
          { labelKey: 'items.equivalences', path: '/production/equivalences' },
          { labelKey: 'items.ofAccess', path: '/production/of-access' },
        ],
      },
    ],
  },
  {
    id: 'hr',
    groupKey: 'groups.hr',
    color: 'cyan',
    icon: Users,
    path: '/hr',
    homePath: '/hr/home',
    items: [
      { labelKey: 'items.employees', path: '/hr/employees' },
      { labelKey: 'items.payRuns', path: '/hr/pay-runs' },
      { labelKey: 'items.paySlips', path: '/hr/pay-slips' },
      { labelKey: 'items.payrollAccounting', path: '/hr/payroll-accounting' },
      { labelKey: 'items.timesheets', path: '/hr/timesheets' },
      { labelKey: 'items.leaveRequests', path: '/hr/leave-requests' },
      { labelKey: 'items.contracts', path: '/hr/contracts' },
      { labelKey: 'items.declarations', path: '/hr/declarations' },
      { labelKey: 'items.payrollCalc', path: '/hr/payroll-calc' },
      { labelKey: 'items.training', path: '/hr/training' },
      { labelKey: 'items.payrollComponents', path: '/hr/payroll-components' },
      { labelKey: 'items.payrollTemplates', path: '/hr/payroll-templates' },
      { labelKey: 'items.salaryAdvances', path: '/hr/salary-advances' },
      { labelKey: 'items.dsn', path: '/hr/dsn' },
      { labelKey: 'items.dpae', path: '/hr/dpae' },
      { labelKey: 'items.legalWatch', path: '/hr/legal-watch' },
      { labelKey: 'items.expenseReports', path: '/hr/expense-reports' },
      { labelKey: 'items.payRecalls', path: '/hr/pay-recalls' },
      { labelKey: 'items.payrollArchives', path: '/hr/payroll-archives' },
      { labelKey: 'items.interviews', path: '/hr/interviews' },
      { labelKey: 'items.hardship', path: '/hr/hardship' },
      { labelKey: 'items.career', path: '/hr/career' },
      { labelKey: 'items.cpf', path: '/hr/cpf' },
      { labelKey: 'items.employeeDocuments', path: '/hr/employee-documents' },
      { labelKey: 'items.workStoppages', path: '/hr/work-stoppages' },
      { labelKey: 'items.medicalExams', path: '/hr/medical-exams' },
      { labelKey: 'items.expenseCategories', path: '/hr/expense-categories' },
      { labelKey: 'items.employeeExit', path: '/hr/employee-exit' },
      { labelKey: 'items.interviewCampaigns', path: '/hr/interview-campaigns' },
      { labelKey: 'items.leaveBalances', path: '/hr/leave-balances' },
      { labelKey: 'items.leavePlanning', path: '/hr/leave-planning' },
      { labelKey: 'items.leaveRules', path: '/hr/leave-rules' },
      { labelKey: 'items.socialDeclarations', path: '/hr/social-declarations' },
      { labelKey: 'items.bdes', path: '/hr/bdes' },
      { labelKey: 'items.documentManagement', path: '/hr/document-management' },
      { labelKey: 'items.rhRequests', path: '/hr/rh-requests' },
      { labelKey: 'items.rhKnowledgeBase', path: '/hr/knowledge-base' },
      { labelKey: 'items.rhReports', path: '/hr/reports' },
      { labelKey: 'items.payrollPreparation', path: '/hr/payroll-preparation' },
      { labelKey: 'items.mealVouchers', path: '/hr/meal-vouchers' },
      { labelKey: 'items.sepaPayments', path: '/hr/sepa-payments' },
    ],
  },
  {
    id: 'projectManagement',
    groupKey: 'groups.projectManagement',
    color: 'rose',
    icon: ClipboardList,
    path: '/project-management',
    homePath: '/project-management',
    sections: [
      {
        subGroupKey: 'subGroups.pmViews',
        hubPath: '/project-management',
        items: [
          { labelKey: 'items.pmHome', path: '/project-management' },
          { labelKey: 'items.pmTasks', path: '/project-management/tasks' },
          { labelKey: 'items.pmKanban', path: '/project-management/kanban' },
          { labelKey: 'items.pmGantt', path: '/project-management/gantt' },
          { labelKey: 'items.pmCalendar', path: '/project-management/calendar' },
        ],
      },
      {
        subGroupKey: 'subGroups.pmAnalysis',
        hubPath: '/project-management/graph',
        items: [
          { labelKey: 'items.pmGraph', path: '/project-management/graph' },
          { labelKey: 'items.pmPivot', path: '/project-management/pivot' },
          { labelKey: 'items.pmBurndown', path: '/project-management/burndown' },
          { labelKey: 'items.pmTimeline', path: '/project-management/timeline' },
        ],
      },
      {
        subGroupKey: 'subGroups.pmPersonal',
        hubPath: '/project-management/my-tasks',
        items: [
          { labelKey: 'items.pmMyTasks', path: '/project-management/my-tasks' },
          { labelKey: 'items.pmWorkload', path: '/project-management/workload' },
          { labelKey: 'items.pmActivity', path: '/project-management/activity' },
          { labelKey: 'items.pmNotifications', path: '/project-management/notifications' },
        ],
      },
      {
        subGroupKey: 'subGroups.pmDisplay',
        hubPath: '/project-management/large-screen',
        items: [
          { labelKey: 'items.pmLargeScreen', path: '/project-management/large-screen' },
        ],
      },
      {
        subGroupKey: 'subGroups.pmVisual',
        hubPath: '/project-management/mind-map',
        items: [
          { labelKey: 'items.pmMindMap', path: '/project-management/mind-map' },
          { labelKey: 'items.pmBox', path: '/project-management/box' },
        ],
      },
      {
        subGroupKey: 'subGroups.pmCollaboration',
        hubPath: '/project-management/doc',
        items: [
          { labelKey: 'items.pmDoc', path: '/project-management/doc' },
          { labelKey: 'items.pmChat', path: '/project-management/chat' },
        ],
      },
    ],
  },
  {
    id: 'dashboards',
    groupKey: 'groups.dashboards',
    color: 'teal',
    icon: BarChart3,
    path: '/dashboard',
    homePath: '/dashboard/home',
    items: [
      { labelKey: 'items.salesDashboard', path: '/dashboard/sales' },
      { labelKey: 'items.purchasesDashboard', path: '/dashboard/purchases' },
      { labelKey: 'items.bankingDashboard', path: '/dashboard/banking' },
      { labelKey: 'items.hrDashboard', path: '/dashboard/hr' },
    ],
  },
  {
    id: 'reporting',
    groupKey: 'groups.reporting',
    color: 'fuchsia',
    icon: PieChart,
    path: '/reporting',
    homePath: '/reporting/home',
    items: [
      { labelKey: 'items.financialDashboard', path: '/reporting/financial' },
      { labelKey: 'items.biReporting', path: '/reporting/bi' },
      { labelKey: 'items.budgetTracking', path: '/reporting/budget' },
    ],
  },
  {
    id: 'system',
    groupKey: 'groups.system',
    color: 'slate',
    icon: Settings,
    path: '/settings',
    homePath: '/settings/home',
    sections: [
      {
        subGroupKey: 'subGroups.configuration',
        hubPath: '/settings/configuration',
        items: [
          { labelKey: 'items.company', path: '/settings/company' },
          { labelKey: 'items.companySettings', path: '/settings/company-settings' },
          { labelKey: 'items.usersMenu', path: '/settings/users' },
          { labelKey: 'items.teamRoles', path: '/settings/team' },
          { labelKey: 'items.currencies', path: '/settings/currencies' },
          { labelKey: 'items.exchangeRates', path: '/settings/exchange-rates' },
          { labelKey: 'items.integrations', path: '/settings/integrations' },
          { labelKey: 'items.modulesSettings', path: '/settings/modules' },
          { labelKey: 'items.multiCompany', path: '/settings/multi-company' },
          { labelKey: 'items.documentTemplates', path: '/settings/document-templates' },
          { labelKey: 'items.apiWebhooks', path: '/settings/api-webhooks' },
          { labelKey: 'items.apiDocs', path: '/settings/api-docs' },
          { labelKey: 'items.emailTemplates', path: '/settings/email-templates' },
          { labelKey: 'items.twoFactor', path: '/settings/2fa' },
          { labelKey: 'items.nf525Audit', path: '/settings/nf525-audit' },
          { labelKey: 'items.taxGrids', path: '/settings/tax-grids' },
          { labelKey: 'items.onboarding', path: '/settings/onboarding' },
        ],
      },
      {
        subGroupKey: 'subGroups.processing',
        hubPath: '/settings/data',
        items: [
          { labelKey: 'items.dataImport', path: '/settings/import' },
          { labelKey: 'items.sageImport', path: '/settings/import/sage' },
          { labelKey: 'items.dataExport', path: '/settings/data-export' },
          { labelKey: 'items.auditLog', path: '/system/audit-log' },
        ],
      },
    ],
  },
]
