export const COUNTRIES = [
  'Afghanistan',
  'Afrique du Sud',
  'Albanie',
  'Algérie',
  'Allemagne',
  'Andorre',
  'Angola',
  'Antigua-et-Barbuda',
  'Arabie saoudite',
  'Argentine',
  'Arménie',
  'Australie',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bahreïn',
  'Bangladesh',
  'Barbade',
  'Belgique',
  'Belize',
  'Bénin',
  'Bhoutan',
  'Biélorussie',
  'Birmanie',
  'Bolivie',
  'Bosnie-Herzégovine',
  'Botswana',
  'Brésil',
  'Brunei',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Centrafrique',
  'Chili',
  'Chine',
  'Chypre',
  'Colombie',
  'Comores',
  'Congo-Brazzaville',
  'Congo-Kinshasa (RDC)',
  'Corée du Nord',
  'Corée du Sud',
  'Costa Rica',
  'Côte d\'Ivoire',
  'Croatie',
  'Cuba',
  'Danemark',
  'Djibouti',
  'Dominique',
  'Égypte',
  'Émirats arabes unis',
  'Équateur',
  'Érythrée',
  'Espagne',
  'Estonie',
  'Eswatini',
  'États-Unis',
  'Éthiopie',
  'Fidji',
  'Finlande',
  'France',
  'Gabon',
  'Gambie',
  'Géorgie',
  'Ghana',
  'Grèce',
  'Grenade',
  'Guatemala',
  'Guinée',
  'Guinée-Bissau',
  'Guinée équatoriale',
  'Guyana',
  'Haïti',
  'Honduras',
  'Hongrie',
  'Îles Marshall',
  'Îles Salomon',
  'Inde',
  'Indonésie',
  'Irak',
  'Iran',
  'Irlande',
  'Islande',
  'Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kirghizistan',
  'Kiribati',
  'Kosovo',
  'Koweït',
  'Laos',
  'Lesotho',
  'Lettonie',
  'Liban',
  'Liberia',
  'Libye',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macédoine du Nord',
  'Madagascar',
  'Malaisie',
  'Malawi',
  'Maldives',
  'Mali',
  'Malte',
  'Maroc',
  'Maurice',
  'Mauritanie',
  'Mexique',
  'Micronésie',
  'Moldavie',
  'Monaco',
  'Mongolie',
  'Monténégro',
  'Mozambique',
  'Namibie',
  'Nauru',
  'Népal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norvège',
  'Nouvelle-Zélande',
  'Oman',
  'Ouganda',
  'Ouzbékistan',
  'Pakistan',
  'Palaos',
  'Palestine',
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pays-Bas',
  'Pérou',
  'Philippines',
  'Pologne',
  'Portugal',
  'Qatar',
  'République dominicaine',
  'République tchèque',
  'Roumanie',
  'Royaume-Uni',
  'Russie',
  'Rwanda',
  'Saint-Kitts-et-Nevis',
  'Saint-Marin',
  'Saint-Vincent-et-les-Grenadines',
  'Sainte-Lucie',
  'Salvador',
  'Samoa',
  'Sao Tomé-et-Principe',
  'Sénégal',
  'Serbie',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  'Slovaquie',
  'Slovénie',
  'Somalie',
  'Soudan',
  'Soudan du Sud',
  'Sri Lanka',
  'Suède',
  'Suisse',
  'Suriname',
  'Syrie',
  'Tadjikistan',
  'Tanzanie',
  'Tchad',
  'Thaïlande',
  'Timor oriental',
  'Togo',
  'Tonga',
  'Trinité-et-Tobago',
  'Tunisie',
  'Turkménistan',
  'Turquie',
  'Tuvalu',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Vietnam',
  'Yémen',
  'Zambie',
  'Zimbabwe',
] as const

export const CURRENCIES = [
  { code: 'EUR', label: 'Euro (€)' },
  { code: 'USD', label: 'Dollar US ($)' },
  { code: 'GBP', label: 'Livre sterling (£)' },
  { code: 'CHF', label: 'Franc suisse (CHF)' },
  { code: 'CAD', label: 'Dollar canadien (C$)' },
  { code: 'AUD', label: 'Dollar australien (A$)' },
  { code: 'NZD', label: 'Dollar néo-zélandais (NZ$)' },
  { code: 'JPY', label: 'Yen japonais (¥)' },
  { code: 'CNY', label: 'Yuan chinois (¥)' },
  { code: 'HKD', label: 'Dollar de Hong Kong (HK$)' },
  { code: 'SGD', label: 'Dollar de Singapour (S$)' },
  { code: 'INR', label: 'Roupie indienne (₹)' },
  { code: 'PKR', label: 'Roupie pakistanaise (₨)' },
  { code: 'BDT', label: 'Taka bangladais (৳)' },
  { code: 'BRL', label: 'Real brésilien (R$)' },
  { code: 'MXN', label: 'Peso mexicain ($)' },
  { code: 'ARS', label: 'Peso argentin ($)' },
  { code: 'COP', label: 'Peso colombien ($)' },
  { code: 'CLP', label: 'Peso chilien ($)' },
  { code: 'PEN', label: 'Sol péruvien (S/)' },
  { code: 'UYU', label: 'Peso uruguayen ($U)' },
  { code: 'VEF', label: 'Bolívar vénézuélien (Bs)' },
  { code: 'RUB', label: 'Rouble russe (₽)' },
  { code: 'UAH', label: 'Hryvnia ukrainienne (₴)' },
  { code: 'PLN', label: 'Zloty polonais (zł)' },
  { code: 'CZK', label: 'Couronne tchèque (Kč)' },
  { code: 'HUF', label: 'Forint hongrois (Ft)' },
  { code: 'RON', label: 'Leu roumain (lei)' },
  { code: 'BGN', label: 'Lev bulgare (лв)' },
  { code: 'SEK', label: 'Couronne suédoise (kr)' },
  { code: 'NOK', label: 'Couronne norvégienne (kr)' },
  { code: 'DKK', label: 'Couronne danoise (kr)' },
  { code: 'ISK', label: 'Couronne islandaise (kr)' },
  { code: 'TRY', label: 'Livre turque (₺)' },
  { code: 'ILS', label: 'Shekel israélien (₪)' },
  { code: 'SAR', label: 'Riyal saoudien (﷼)' },
  { code: 'AED', label: 'Dirham des EAU (د.إ)' },
  { code: 'QAR', label: 'Riyal qatari (﷼)' },
  { code: 'KWD', label: 'Dinar koweïtien (د.ك)' },
  { code: 'BHD', label: 'Dinar bahreïni (د.ب)' },
  { code: 'OMR', label: 'Rial omanais (﷼)' },
  { code: 'JOD', label: 'Dinar jordanien (د.ا)' },
  { code: 'LBP', label: 'Livre libanaise (ل.ل)' },
  { code: 'IRR', label: 'Rial iranien (﷼)' },
  { code: 'IQD', label: 'Dinar irakien (ع.د)' },
  { code: 'EGP', label: 'Livre égyptienne (£E)' },
  { code: 'MAD', label: 'Dirham marocain (DH)' },
  { code: 'DZD', label: 'Dinar algérien (DA)' },
  { code: 'TND', label: 'Dinar tunisien (DT)' },
  { code: 'LYD', label: 'Dinar libyen (ل.د)' },
  { code: 'SDG', label: 'Livre soudanaise (£S)' },
  { code: 'ETB', label: 'Birr éthiopien (Br)' },
  { code: 'ERN', label: 'Nakfa érythréenne (Nfk)' },
  { code: 'DJF', label: 'Franc djiboutien (Fdj)' },
  { code: 'SOS', label: 'Shilling somalien (Sh)' },
  { code: 'KES', label: 'Shilling kényan (KSh)' },
  { code: 'UGX', label: 'Shilling ougandais (USh)' },
  { code: 'TZS', label: 'Shilling tanzanien (TSh)' },
  { code: 'RWF', label: 'Franc rwandais (RF)' },
  { code: 'BIF', label: 'Franc burundais (FBu)' },
  { code: 'XOF', label: 'Franc CFA (XOF)' },
  { code: 'XAF', label: 'Franc CFA (XAF)' },
  { code: 'XPF', label: 'Franc CFP (XPF)' },
  { code: 'GMD', label: 'Dalasi gambien (D)' },
  { code: 'GNF', label: 'Franc guinéen (FG)' },
  { code: 'LRD', label: 'Dollar libérien (L$)' },
  { code: 'SLL', label: 'Leone sierra-léonais (Le)' },
  { code: 'GHS', label: 'Cedi ghanéen (₵)' },
  { code: 'NGN', label: 'Naira nigérian (₦)' },
  { code: 'ZAR', label: 'Rand sud-africain (R)' },
  { code: 'NAD', label: 'Dollar namibien (N$)' },
  { code: 'BWP', label: 'Pula botswanais (P)' },
  { code: 'ZMW', label: 'Kwacha zambien (ZK)' },
  { code: 'ZWL', label: 'Dollar zimbabwéen (Z$)' },
  { code: 'MZN', label: 'Metical mozambicain (MT)' },
  { code: 'AOA', label: 'Kwanza angolais (Kz)' },
  { code: 'CDF', label: 'Franc congolais (FC)' },
  { code: 'XCG', label: 'Gourde haïtienne (G)' },
  { code: 'HTG', label: 'Gourde haïtienne (G)' },
  { code: 'DOP', label: 'Peso dominicain (RD$)' },
  { code: 'GTQ', label: 'Quetzal guatémaltèque (Q)' },
  { code: 'HNL', label: 'Lempira hondurien (L)' },
  { code: 'NIO', label: 'Córdoba nicaraguayen (C$)' },
  { code: 'PAB', label: 'Balboa panaméen (B/.)' },
  { code: 'CRC', label: 'Colón costaricain (₡)' },
  { code: 'CUP', label: 'Peso cubain ($)' },
  { code: 'JMD', label: 'Dollar jamaïcain (J$)' },
  { code: 'TTD', label: 'Dollar trinidadien (TT$)' },
  { code: 'BBD', label: 'Dollar barbadien (Bds$)' },
  { code: 'BSD', label: 'Dollar bahaméen (B$)' },
  { code: 'BZD', label: 'Dollar bélizien (BZ$)' },
  { code: 'GYD', label: 'Dollar guyanien (G$)' },
  { code: 'SRD', label: 'Dollar surinamien (Sr$)' },
  { code: 'KRW', label: 'Won sud-coréen (₩)' },
  { code: 'KPW', label: 'Won nord-coréen (₩)' },
  { code: 'MNT', label: 'Tugrik mongol (₮)' },
  { code: 'KHR', label: 'Riel cambodgien (៛)' },
  { code: 'LAK', label: 'Kip laotien (₭)' },
  { code: 'VND', label: 'Dong vietnamien (₫)' },
  { code: 'THB', label: 'Baht thaïlandais (฿)' },
  { code: 'MMK', label: 'Kyat birman (K)' },
  { code: 'LKR', label: 'Roupie sri-lankaise (Rs)' },
  { code: 'MVR', label: 'Rufiyaa maldivienne (Rf)' },
  { code: 'NPR', label: 'Roupie népalaise (₨)' },
  { code: 'AFN', label: 'Afghani afghan (؋)' },
  { code: 'TJS', label: 'Somoni tadjik (ЅМ)' },
  { code: 'KGS', label: 'Som kirghize (с)' },
  { code: 'UZS', label: 'Sum ouzbek (so\'m)' },
  { code: 'KZT', label: 'Tenge kazakh (₸)' },
  { code: 'AZN', label: 'Manat azerbaïdjanais (₼)' },
  { code: 'GEL', label: 'Lari géorgien (₾)' },
  { code: 'AMD', label: 'Dram arménien (֏)' },
  { code: 'MDL', label: 'Leu moldave (L)' },
  { code: 'ALL', label: 'Lek albanais (L)' },
  { code: 'RSD', label: 'Dinar serbe (дин)' },
  { code: 'BAM', label: 'Mark convertible (KM)' },
  { code: 'MKD', label: 'Denar macédonien (ден)' },
  { code: 'BYN', label: 'Rouble biélorusse (Br)' },
  { code: 'FJD', label: 'Dollar fidjien (FJ$)' },
  { code: 'PGK', label: 'Kina papouan-néo-guinéen (K)' },
  { code: 'SBD', label: 'Dollar des îles Salomon (SI$)' },
  { code: 'VUV', label: 'Vatu vanuatais (VT)' },
  { code: 'WST', label: 'Tala samoan (WS$)' },
  { code: 'TOP', label: 'Pa\'anga tongienne (T$)' },
  { code: 'AUD', label: 'Dollar australien (A$)' },
] as const
